src/logistration/tests/LoginHelpLinks.test.jsx
src/logistration/tests/LoginPage.test.jsx
src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap

Tests added for:
- LoginPage
- LoginHelpLinks
[VAN-60](https://openedx.atlassian.net/browse/VAN-60)

Add tests for login functionality

---

public/index.html
src/reset-password/ResetPasswordPage.jsx
src/reset-password/data/service.js
src/reset-password/messages.js
src/reset-password/tests/ResetPasswordPage.test.jsx
src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap

On old password reset page we use backend endpoint to validate password, added same functionality for the MFE.
VAN-87

Add backend validation on password reset page.

---

src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap

Removed space between input and help text

---

package-lock.json
package.json
src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
src/logistration/RegistrationFailure.jsx
src/logistration/RegistrationPage.jsx
src/logistration/data/actions.js
src/logistration/data/reducers.js
src/logistration/data/sagas.js
src/logistration/tests/RegistrationPage.test.jsx
src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap
src/logistration/tests/__snapshots__/RegistrationPage.test.jsx.snap
src/reset-password/ResetFailure.jsx
src/reset-password/ResetSuccess.jsx
src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap

Adds error handling to registration page flow.

---

src/logistration/ConfirmationAlert.jsx
src/logistration/tests/__snapshots__/ConfirmationAlert.test.jsx.snap
src/reset-password/ResetFailure.jsx
src/reset-password/ResetSuccess.jsx
src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap

Moving from Custom alert to paragon alert widget.

---

src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
src/logistration/LoginHelpLinks.jsx
src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap

Fix need help signing in button styling.

---

src/RegisterFaIcons.jsx
src/data/constants.js
src/index.jsx
src/logistration/LoginHelpLinks.jsx
src/logistration/LoginPage.jsx
src/logistration/RedirectLogistration.jsx
src/logistration/SocialAuthProviders.jsx
src/logistration/ThirdPartyAuthAlert.jsx
src/logistration/_style.scss
src/logistration/data/constants.js
src/logistration/data/service.js
src/logistration/tests/LoginPage.test.jsx
src/logistration/tests/SocialAuthProviders.test.jsx
src/logistration/tests/ThirdPartyAuthAlert.test.jsx
src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap
src/logistration/tests/__snapshots__/SocialAuthProviders.test.jsx.snap
src/logistration/tests/__snapshots__/ThirdPartyAuthAlert.test.jsx.snap

Add third party auth providers
- Added TPA providers to login page
- Added error component to deal with third party auth error
Following are generated using the prod and stage TPA context.
[VAN-92](https://openedx.atlassian.net/browse/VAN-92)

add social auth

---

package-lock.json
package.json
src/index.scss

Remove footer from dependencies.

---

src/logistration/LoginPage.jsx
src/logistration/RegistrationPage.jsx
src/logistration/SocialAuthProviders.jsx
src/logistration/ThirdPartyAuthAlert.jsx
src/logistration/_style.scss
src/logistration/messages.jsx
src/logistration/tests/RegistrationPage.test.jsx
src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap
src/logistration/tests/__snapshots__/RegistrationPage.test.jsx.snap

- Added SSO to register page
- Added tests for SSO
- Updated few css classes
Note: This is missing the autofill register form functionality that populates user information received from social auth. It will be covered when we use formik for forms.

Add SSO to register page

---

src/data/constants.js
src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/tests/ForgotPasswordPage.test.jsx
src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
src/logistration/LoginPage.jsx
src/logistration/RegistrationPage.jsx
src/logistration/data/reducers.js
src/logistration/messages.jsx
src/logistration/tests/LoginPage.test.jsx
src/logistration/tests/RegistrationPage.test.jsx
src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap
src/logistration/tests/__snapshots__/RegistrationPage.test.jsx.snap
src/reset-password/ResetPasswordPage.jsx
src/reset-password/tests/ResetPasswordPage.test.jsx
src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap

[VAN-123](https://openedx.atlassian.net/browse/VAN-123)
Added stateful button component from paragon to
- LoginPage
- RegistrationPage
- ForgetPasswordPage
- ResetPasswordPage

Add stateful buttons on forms

---

src/logistration/RegistrationPage.jsx
src/logistration/tests/__snapshots__/RegistrationPage.test.jsx.snap

registration fields order updated

---

src/logistration/LoginFailure.jsx
src/logistration/LoginHelpLinks.jsx
src/logistration/LoginPage.jsx
src/logistration/RegistrationFailure.jsx
src/logistration/RegistrationPage.jsx
src/logistration/messages.jsx
src/logistration/tests/LoginHelpLinks.test.jsx
src/logistration/tests/RegistrationPage.test.jsx
src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap
src/logistration/tests/__snapshots__/RegistrationPage.test.jsx.snap

Added missing translation strings for Login and Register Page.
Ticket: https://openedx.atlassian.net/browse/VAN-130

VAN-130: Add translation strings

---

.gitignore
src/logistration/LoginFailure.jsx
src/logistration/LoginPage.jsx
src/logistration/data/constants.js
src/logistration/tests/LoginFailure.test.jsx
src/logistration/tests/LoginPage.test.jsx
src/logistration/tests/__snapshots__/LoginFailure.test.jsx.snap
src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap

- Added `INACTIVE_USER` error check in LoginFailure component
- Removed inline style
- Replace links and headings with Alert.Link and Alert.Heading (https://edx.github.io/paragon/components/alert)
- Removed test from LoginPage as those don't contribute to coverage and should be added to LoginFailure tests
[VAN-217](https://openedx.atlassian.net/browse/VAN-217)

Add inactive user error message

---

src/logistration/RegistrationPage.jsx
src/logistration/data/actions.js
src/logistration/data/reducers.js
src/logistration/data/sagas.js
src/logistration/data/service.js
src/logistration/data/tests/sagas.test.js
src/logistration/messages.jsx
src/logistration/tests/RegistrationPage.test.jsx
src/logistration/tests/__snapshots__/RegistrationPage.test.jsx.snap

This patch adds realtime/ validations for;
*) name
*) fullname
*) password
*) email
VAN-30

Adds realtime validations to register form.

---

.gitignore
src/logistration/RegistrationPage.jsx
src/logistration/data/sagas.js
src/logistration/data/service.js
src/logistration/data/tests/sagas.test.js
src/logistration/messages.jsx
src/logistration/tests/RegistrationPage.test.jsx
src/logistration/tests/__snapshots__/RegistrationPage.test.jsx.snap
src/setupTest.js

Fixed form submission issues on the first click and with optional fields check. Also fixed some warnings and did some refactoring as well.
VAN-225, VAN-206

Fix form submission issues.

---

src/logistration/RegistrationPage.jsx
src/logistration/tests/RegistrationPage.test.jsx
src/logistration/tests/__snapshots__/RegistrationPage.test.jsx.snap

When registering via sso, we don't need to ask for password on registration form.
[VAN-224](https://openedx.atlassian.net/browse/VAN-224)
-----

Display form with no password field for SSO

---

package-lock.json
package.json
src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
src/logistration/RegistrationPage.jsx

Apply formik form validations to Password reset form.
VAN-126

apply formik to reset form

---

src/logistration/RegistrationPage.jsx
src/logistration/_style.scss
src/logistration/messages.jsx

Rearrange optional fields to make them compliant with old monolith

Rearrange optional fields

---

src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/messages.js
src/forgot-password/tests/ForgotPasswordPage.test.jsx
src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap

VAN-212
-----------------------------------------------------------------------------------------------------------------------------

fix email validation error message.

---

src/data/constants.js
src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/tests/ForgotPasswordPage.test.jsx

Updated the regex to be same as FE 
[VAN-211](https://openedx.atlassian.net/browse/VAN-211)

update regex for email on forgot password page

---

src/logistration/RegistrationFailure.jsx
src/logistration/RegistrationPage.jsx
src/logistration/_style.scss
src/logistration/messages.jsx
src/logistration/tests/RegistrationPage.test.jsx
src/setupTest.js

*) Empty fields error messages
*) Removes onChange validations
VAN-204

This patches fixes following;

---

src/logistration/_style.scss
src/reset-password/ResetPasswordPage.jsx
src/reset-password/Spinner.jsx
src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap

re-align loader

---

src/data/constants.js
src/forgot-password/tests/ForgotPasswordPage.test.jsx
src/logistration/LoginHelpLinks.jsx
src/logistration/LoginPage.jsx
src/logistration/messages.jsx
src/logistration/tests/LoginHelpLinks.test.jsx
src/logistration/tests/LoginPage.test.jsx
src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap

Add enterprise login link to MFE so that enterprise user would be redirected to enterprise login page.
VAN-214

add enterprise login link

---

src/logistration/LoginPage.jsx
src/logistration/RegistrationPage.jsx
src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap
src/logistration/tests/__snapshots__/RegistrationPage.test.jsx.snap

Fix max-width issue with social auth buttons.

---

src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
src/logistration/InstitutionLogistration.jsx
src/logistration/LoginPage.jsx
src/logistration/RegistrationPage.jsx
src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap
src/logistration/tests/__snapshots__/RegistrationPage.test.jsx.snap

VAN-249
VAN-252
VAN-265
VAN-269
VAN-256
VAN-257
VAN-267
VAN-261
VAN-263

fix css styles

---

src/logistration/_style.scss
src/reset-password/Spinner.jsx
src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap

Fix loader height so that it is no longer scrollable.

fix spinner height

---

src/logistration/InstitutionLogistration.jsx
src/logistration/LoginPage.jsx
src/logistration/RegistrationPage.jsx
src/logistration/messages.jsx
src/logistration/tests/LoginPage.test.jsx
src/logistration/tests/RegistrationPage.test.jsx
src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap
src/logistration/tests/__snapshots__/RegistrationPage.test.jsx.snap

VAN-259
VAN-258
VAN-253
VAN-251
VAN-262
VAN-266

fix spacing issues on login and register page

---

src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
src/logistration/InstitutionLogistration.jsx
src/logistration/LoginPage.jsx
src/logistration/_style.scss
src/logistration/messages.jsx
src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap
src/reset-password/ResetFailure.jsx
src/reset-password/ResetPasswordPage.jsx
src/reset-password/ResetSuccess.jsx
src/reset-password/tests/ResetPasswordPage.test.jsx
src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap

fix missing issues related to branding.

fix missing branding issues

---

src/logistration/RegistrationPage.jsx
src/logistration/_style.scss
src/logistration/tests/RegistrationPage.test.jsx
src/logistration/tests/__snapshots__/RegistrationPage.test.jsx.snap

Padding between browser frame and form should be 10px.
VAN-260

Add consistent padding between form and browser frame

---

src/logistration/RegistrationFailure.jsx
src/logistration/RegistrationPage.jsx
src/logistration/data/actions.js
src/logistration/data/reducers.js
src/logistration/data/sagas.js
src/logistration/data/tests/sagas.test.js
src/logistration/messages.jsx
src/logistration/tests/RegistrationPage.test.jsx
src/logistration/tests/__snapshots__/RegistrationPage.test.jsx.snap

VAN-283, VAN-293, VAN-120 part-1

Adds missing backend format validations error on submit.

---

package-lock.json
package.json
src/data/constants.js
src/logistration/LoginPage.jsx
src/logistration/RegistrationPage.jsx
src/logistration/data/reducers.js
src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap
src/logistration/tests/__snapshots__/RegistrationPage.test.jsx.snap

VAN-140
https://user-images.githubusercontent.com/8156837/104296339-51b41d80-54e3-11eb-9f23-01030c38a92e.mov
When API fails:
https://user-images.githubusercontent.com/8156837/103946007-e3c0cc80-5157-11eb-9245-92abbc45fcf4.mov

Skeleton added for the third party auth buttons

---

src/logistration/InstitutionLogistration.jsx
src/logistration/LoginPage.jsx
src/logistration/RegistrationPage.jsx
src/logistration/_style.scss
src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap
src/logistration/tests/__snapshots__/RegistrationPage.test.jsx.snap

fix signin-form-width-issue

---

src/logistration/LoginPage.jsx
src/logistration/RegistrationPage.jsx
src/logistration/data/service.js
src/reset-password/data/service.js

Changed login/registration endpoints to match monolith FE. Also fixed a warning and removed an extra call to `login_refresh`.
VAN-107
VAN-12

Change login and registration API endpoints.

---

src/index.jsx
src/logistration/AccountActivationMessage.jsx
src/logistration/LoginFailure.jsx
src/logistration/LoginPage.jsx
src/logistration/data/constants.js
src/logistration/messages.jsx
src/logistration/tests/AccountActivationMessage.test.jsx
src/logistration/tests/LoginPage.test.jsx
src/logistration/tests/__snapshots__/LoginFailure.test.jsx.snap

Show messages based on the query paran recieved during the redirect after
account activation link is clicked
VAN-304

Add account activation messages

---

src/logistration/RegistrationFailure.jsx
src/logistration/RegistrationPage.jsx

Scrolling was not working for error message
changes on form submission. useEffect was not
calling callback on its dependency change ie error message
.This patch would fix this.

Fix scrolling issue.

---

src/login/data/sagas.js
src/login/data/tests/sagas.test.js
src/login/tests/LoginPage.test.jsx
src/reset-password/ResetPasswordPage.jsx
src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap

- updated login sagas to include forbidden request error message
- updated tests for sagas
- fixed some css changes made previously

add missing changes after app rename

---

src/login/LoginHelpLinks.jsx
src/login/LoginPage.jsx
src/login/tests/LoginHelpLinks.test.jsx
src/login/tests/LoginPage.test.jsx
src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx
src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap

This patch adds tracking and page events destined for GA.
VAN-282

Adds frontend events for Google Analytics.

---

src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/tests/ForgotPasswordPage.test.jsx

Adds missing GA event for forgot-password.

---

src/common-components/InstitutionLogistration.jsx

addressed ux feedback

---

src/login/LoginPage.jsx
src/register/RegistrationPage.jsx

This would fix multiple GA event firing
on component rerendering. Moving it to
constructor would invoke it once on page
load.

Fix multiple event firing on rerenders.

---

src/register/RegistrationPage.jsx
src/register/messages.jsx
src/register/tests/RegistrationPage.test.jsx
src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap

**Before:**
**After:**
VAN-324

Adds UX suggested changes.

---

src/register/RegistrationFailure.jsx
src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
src/reset-password/InvalidToken.jsx
src/reset-password/ResetPasswordPage.jsx
src/reset-password/ResetSuccess.jsx
src/reset-password/messages.js
src/reset-password/tests/ResetPasswordPage.test.jsx
src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap

- Added empty form error message 
- Fixed stateful button
- Take page focus to top of page when rate limit error is shown
- Use same color header as the body
[VAN-299](https://openedx.atlassian.net/browse/VAN-299)

Zamir/van 299/fix reset password page bugs

---

src/common-components/ThirdPartyAuthAlert.jsx
src/common-components/tests/__snapshots__/ThirdPartyAuthAlert.test.jsx.snap
src/register/RegistrationPage.jsx
src/register/messages.jsx
src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap

1) Space in sign-in link
2) Stateful button now shows states.
3) SSO pipeline message on the register page should use success alert instead warning style
VAN-297

Fix register page

---

src/register/RegistrationPage.jsx

1) On ratelimiting fields would show locally
handled error message below them. Incase
of multiple errors, only the first one is
displayed.
2) On change is added to country field to
handle value toggled either via keyboard
or mouse.

Show field validations below them on ratelimiting

---

src/common-components/ThirdPartyAuthAlert.jsx
src/common-components/tests/__snapshots__/ThirdPartyAuthAlert.test.jsx.snap
src/register/RegistrationPage.jsx
src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap

**) Fix TPA Alert messages
**) Fix TPA options incorrect text
VAN-297

Forward Fix VAN-297

---

src/_style.scss

Increase SSO buttons width.

---

src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
src/login/LoginPage.jsx
src/login/tests/__snapshots__/LoginPage.test.jsx.snap

Add loader icon to Login/register page.

add loader to form buttons

---

src/register/RegistrationPage.jsx
src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap

Remove margin bottom from register fields

---

openedx.yaml
package-lock.json
package.json

Updated paragon version to latest.

---

src/login/LoginPage.jsx
src/login/messages.jsx
src/login/tests/__snapshots__/LoginPage.test.jsx.snap

Fix the error sequences of email/password fields

fix error message sequence

---

src/reset-password/ResetPasswordPage.jsx
src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap

| Before  | After |
| ------------- | ------------- |
[VAN-299](https://openedx.atlassian.net/browse/VAN-299)

VAN-299: Add header to Password Reset Alert

---

package-lock.json
package.json
src/common-components/HeaderLayout.jsx
src/forgot-password/tests/ForgotPasswordPage.test.jsx
src/index.scss
src/login/tests/LoginPage.test.jsx
src/register/tests/RegistrationPage.test.jsx
src/reset-password/tests/ResetPasswordPage.test.jsx

cookie banner added

---

src/common-components/APIFailureMessage.jsx
src/data/constants.js
src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/RequestInProgressAlert.jsx
src/forgot-password/data/reducers.js
src/forgot-password/data/tests/sagas.test.js
src/forgot-password/messages.js
src/forgot-password/tests/ForgotPasswordPage.test.jsx
src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
src/reset-password/ResetPasswordPage.jsx

Notes:
- Use paragon component for email helper text
- On submitting a response if errors are generated take page focus to the top of the page on errors alert box.
- On empty form submission mandatory field error is displayed below the field
- Rate limit error alert should be consistent as the one that appears on FE
| Before  | After |
| ------------- | ------------- |
| <img width="567" alt="Screenshot 2021-01-27 at 4 46 36 PM" src="https://user-images.githubusercontent.com/40633976/105986945-638ae880-60bf-11eb-9c9a-a6ba7aa3f6d3.png"> | <img width="567" alt="Screenshot 2021-01-27 at 4 46 13 PM" src="https://user-images.githubusercontent.com/40633976/105986968-6980c980-60bf-11eb-9425-fcb46b19ec41.png"> |
-----
**Email Validation:**
----- …

Fix Password Assistance Bugs

---

src/forgot-password/data/tests/sagas.test.js
src/login/LoginFailure.jsx
src/login/data/constants.js
src/login/messages.jsx

VAN-342
Platform PR for error codes https://github.com/edx/edx-platform/pull/26404

Use errorCode for login failure messages.

---

src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
src/login/LoginHelpLinks.jsx
src/login/tests/__snapshots__/LoginPage.test.jsx.snap
src/register/RegistrationPage.jsx
src/register/messages.jsx
src/register/tests/RegistrationPage.test.jsx
src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap

Added fields errors in case of submit

---

src/reset-password/ResetPasswordPage.jsx
src/reset-password/tests/ResetPasswordPage.test.jsx
src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap

Bugs: 
- If empty field is submitted after there was format error, the empty field message was not shown
- Empty error message box was shown on successful password submission

VAN-299/fix_error_message_preference

---

src/_style.scss
src/common-components/InstitutionLogistration.jsx
src/login/LoginPage.jsx
src/login/tests/__snapshots__/LoginPage.test.jsx.snap
src/register/RegistrationPage.jsx
src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap

Also removed custom PX size classes and used bootstrap classes.
VAN-359

Add underline on sign in link.

---

src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

VAN-351
VAN-354
VAN-350
VAN-357

registration errors fixed reported during bugbash

---

.gitignore
package-lock.json
package.json

Update package version for header

update header package version

---

src/login/LoginFailure.jsx
src/login/LoginPage.jsx
src/login/data/constants.js
src/login/tests/LoginFailure.test.jsx
src/login/tests/LoginPage.test.jsx
src/login/tests/__snapshots__/LoginPage.test.jsx.snap
src/register/tests/RegistrationPage.test.jsx

Changes: 
- On form submission check for frontend validations first before submitting.
- On form submission error should be displayed above and below the field.
- No errors should be updated on onChange
- Errors below fields are updated on blur event
[VAN-345](https://openedx.atlassian.net/browse/VAN-345)

Fix Login Page Validations

---

src/register/RegistrationPage.jsx

Reduce spacing between tos and optional field.

---

src/common-components/AuthnValidationFormGroup.jsx
src/register/RegistrationPage.jsx
src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap

Using AuthnValidationFormGroup for optional fields to enable
focusin/out behaviour for label
VAN-325

Fix optional select fields be consistent with other select box.

---

src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

backend validations updated for registration form

---

src/forgot-password/data/service.js
src/register/data/service.js
src/reset-password/data/service.js

This would removes unnecessary csrf token and options calls from multiple endpoints.
VAN-370

Removes option call from validation endpoint

---

.env.development
src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

Space is causing problems with `frontend_build.py` deployment script, changed to a comma.

Fix optional fields issue.

---

src/forgot-password/data/service.js

Changed it back to `getAuthenticatedHttpClient()`

Forgot password endpoint require a CSRF token.

---

src/register/data/service.js

`getHttpClient` doesn't seems to be working as expected, changing it back to `getAuthenticatedHttpClient`.

Fix registration process.

---

src/common-components/EnterpriseSSO.jsx
src/common-components/messages.jsx

Changes | EnterpriseSSO Flow
:------------ | :-------------|
Make the sign-in/register button full width | :white_check_mark: 
Fix title heading |  :white_check_mark: 
VAN-42

Minor changes in UX.

---

src/common-components/messages.jsx
src/forgot-password/tests/ForgotPasswordPage.test.jsx
src/login/messages.jsx
src/login/tests/AccountActivationMessage.test.jsx
src/register/messages.jsx
src/reset-password/ResetSuccess.jsx
src/reset-password/tests/ResetPasswordPage.test.jsx
src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap

Some strings were missed in the last PR and I have updated those here.

VAN-393: sentence case missing strings

---

src/common-components/APIFailureMessage.jsx
src/forgot-password/messages.js
src/forgot-password/tests/ForgotPasswordPage.test.jsx

The changes in this PR will make the error banner position consistent with the form shown with it.
Here is the screenshot:
[VAN-281](https://openedx.atlassian.net/browse/VAN-281)

make banner alignment consistent with form

---

src/_style.scss
src/common-components/AuthnValidationFormGroup.jsx
src/common-components/tests/AuthnValidationFormGroup.test.jsx
src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
src/login/tests/__snapshots__/LoginPage.test.jsx.snap
src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx
src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap

Ticket: https://openedx.atlassian.net/browse/VAN-385

VAN-385: add label for each input field

---

src/_style.scss
src/register/RegistrationPage.jsx
src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap

|Before|After|
|----|----|
|<img width="558" alt="Screenshot 2021-02-24 at 3 13 38 PM" src="https://user-images.githubusercontent.com/40633976/108985543-fc0e8b80-76b2-11eb-8e2a-d74c60497028.png">|<img width="558" alt="Screenshot 2021-02-24 at 3 14 19 PM" src="https://user-images.githubusercontent.com/40633976/108985553-ff097c00-76b2-11eb-9f1f-0b3bd6fc2d7b.png">

Remove unwanted space from hyperlink

---

src/common-components/AuthnValidationFormGroup.jsx
src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap

The changes in this PR will remove the inconsistency in the font-weight specifically in drop downs on registration page.
[VAN-378](https://openedx.atlassian.net/browse/VAN-378)

fix font inconsistency

---

src/login/LoginHelpLinks.jsx

Reverts edx/frontend-app-authn#166

Revert "Fixed help link color."

---

package-lock.json
package.json
src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/messages.js
src/login/LoginPage.jsx
src/login/messages.jsx
src/register/RegistrationPage.jsx
src/register/messages.jsx
src/reset-password/InvalidToken.jsx
src/reset-password/ResetPasswordPage.jsx
src/reset-password/ResetSuccess.jsx
src/reset-password/messages.js

react helmet package added to change each page title

---

package-lock.json
package.json
src/index.jsx

App not workinng in IE 11 with babel-polyfill.

Replace babel-polyfill with core-js and regenerator-runtime.

---

src/register/RegistrationFailure.jsx

Changes made in https://github.com/edx/edx-platform/pull/26821 will update how the backend returns response. This PR makes sure that backend changes don't break the registration workflow on MFE.

update registration failure message

---

src/login/data/sagas.js
src/login/data/tests/sagas.test.js

Log error only for non 4XX responses.

Log info for 4XX responses.

---

src/forgot-password/data/sagas.js
src/forgot-password/data/tests/sagas.test.js
src/register/data/sagas.js
src/register/data/tests/sagas.test.js
src/reset-password/data/sagas.js
src/reset-password/data/tests/sagas.test.js

Change logError into logInfo for 4XX responses.

---

src/common-components/AuthnValidationFormGroup.jsx
src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
src/login/LoginPage.jsx
src/login/tests/__snapshots__/LoginPage.test.jsx.snap
src/register/OptionalFields.jsx
src/register/RegistrationPage.jsx
src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
src/reset-password/ResetPasswordPage.jsx
src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap

Add 3:1 contrast to all form text field.

---

src/register/RegistrationPage.jsx
src/register/data/actions.js
src/register/tests/RegistrationPage.test.jsx

Added a new param to payload in registration page. This tracks the total time it took user to register.
VAN-413

Track total time it takes users to register

---

src/data/utils/dataUtils.js
src/data/utils/index.js
src/login/LoginPage.jsx
src/login/tests/LoginPage.test.jsx
src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

[VAN-415](https://openedx.atlassian.net/browse/VAN-415)

Fix enrolment through SSO login/register.

---

src/common-components/HeaderLayout.jsx

Add id attribute to the Header's main tag so that it would be focusable via SkipNav.
VAN-379

add id attr

---

src/data/utils/dataUtils.js
src/login/LoginPage.jsx
src/login/tests/LoginPage.test.jsx
src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

redirect MFE to tpa url if tpa_hint is secondary provider
https://user-images.githubusercontent.com/8156837/112527690-21cba500-8dc5-11eb-80c4-38b23d1e1154.mov
VAN-401

redirect MFE to tpa url if tpa_hint

---

package-lock.json
package.json
src/common-components/AuthnValidationFormGroup.jsx
src/common-components/tests/AuthnValidationFormGroup.test.jsx
src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
src/login/LoginPage.jsx
src/login/tests/__snapshots__/LoginPage.test.jsx.snap
src/register/OptionalFields.jsx
src/register/RegistrationPage.jsx
src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
src/reset-password/ResetPasswordPage.jsx
src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap

Reverts edx/frontend-app-authn#220
Latest paragon version causing some issues with the current implementation.

Revert "Add 3:1 contrast to all form text field."

---

src/common-components/AuthnValidationFormGroup.jsx
src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
src/login/tests/__snapshots__/LoginPage.test.jsx.snap
src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap

Allow browser autocomplete when appropriate for personal info edit controls.
VAN-383

autocomplete form input

---

src/common-components/AuthnValidationFormGroup.jsx
src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

Used local state to store `fieldName` instead of sending it back-and-forth between frontend and backend. Also fixed select icon related issue.

fix select icon issue and some code refactor

---

src/common-components/tests/BaseComponent.test.jsx

Write this basic test to complete test coverage 100%.

Base component unit test

---

src/register/RegistrationPage.jsx

Provide default values for TOS_AND_HONOR_CODE and PRIVACY_POLICY

Provide default value for links

---

src/_style.scss
src/common-components/FormGroup.jsx
src/register/RegistrationPage.jsx
src/register/UsernameField.jsx
src/register/data/selectors.js
src/register/messages.jsx
src/register/tests/RegistrationPage.test.jsx

Added username suggestions functionality according to redesign.
Backend PR: https://github.com/edx/edx-platform/pull/27387
https://user-images.githubusercontent.com/2851134/115433041-82ad9800-a220-11eb-92b7-f9eb8d6ae4d2.mp4
VAN-52

add username suggestions functionality

---

src/login/data/service.js

Upgrade login api end point which also supports username along with email of the user to login.
VAN-446

upgrade login api endpoint

---

src/common-components/data/service.js
src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

- get country code based on IP address from server
- set country automatically based on IP address in registration form
VAN-366

Pre populate country

---

src/_style.scss
src/common-components/PasswordField.jsx
src/common-components/tests/FormField.test.jsx

https://user-images.githubusercontent.com/8156837/115454535-4f780280-a23a-11eb-916b-70bb2e6bef82.mov
VAN-340

tooltip design updated

---

src/login/LoginFailure.jsx
src/login/LoginPage.jsx
src/login/data/actions.js
src/login/data/reducers.js
src/login/messages.jsx
src/login/tests/LoginFailure.test.jsx
src/login/tests/LoginPage.test.jsx

Redesign login error messages
- generic error message appears on top of the page
- update field related error messages
VAN-396
**Before** 
**After**

Redesign login error messages

---

src/login/LoginPage.jsx
src/login/tests/LoginPage.test.jsx

- clean login form invalid error message code.
VAN-396
**Other Discreption**
- Redesign login form invalid error message PR has already merged into `redesign-master` branch.

Login form invalid error message

---

src/register/RegistrationPage.jsx
src/register/UsernameField.jsx
src/register/data/actions.js
src/register/data/reducers.js
src/register/data/selectors.js
src/register/data/tests/reducers.test.js
src/register/tests/RegistrationPage.test.jsx

Also refactored some code.
VAN-52

improve username suggestions experience

---

src/_style.scss
src/register/UsernameField.jsx

Adjusted font sizes and margin according to figma design.
VAN-52

Adjusted username suggestions font size

---

src/common-components/Logistration.jsx
src/common-components/messages.jsx
src/common-components/tests/__snapshots__/ThirdPartyAuthAlert.test.jsx.snap

- updated header of sso alert message
- updated toggle text from "Login" --> "Sign in" 
Ticket Reference:
- https://openedx.atlassian.net/browse/VAN-475
- https://openedx.atlassian.net/browse/VAN-482

fix: update header and toggle text based on figma designs

---

src/common-components/AuthnValidationFormGroup.jsx
src/common-components/tests/AuthnValidationFormGroup.test.jsx
src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

- registration form input fields related error messages clear on focus in.
VAN-464

Clear error message on focus in

---

src/register/RegistrationFailure.jsx
src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

- Scroll to error message on every submit action of registration page
VAN-478

Scroll to on top error message

---

package-lock.json
package.json
src/_style.scss
src/common-components/AlertDismissible.jsx
src/common-components/FormGroup.jsx
src/common-components/index.jsx
src/data/constants.js
src/register/RegistrationPage.jsx
src/register/messages.jsx
src/register/tests/RegistrationPage.test.jsx
webpack.prod.config.js

Add did u mean feature which will validate top level domain and service provider domain.
https://openedx.atlassian.net/browse/VAN-287
After shipping this change to staging and production environment, a user can see the suggestions related to Top Level as well as Service level domains.

add did u mean email feature

---

src/register/RegistrationPage.jsx

Refactored the checks to avoid any backend calls in case of any email suggestions.

refactor did you mean validations

---

src/_style.scss

linear gradient for primary image on large screen decreased.

gradient updated for large screen

---

src/_style.scss
src/common-components/EnterpriseSSO.jsx
src/common-components/Logistration.jsx
src/login/tests/LoginPage.test.jsx
src/register/tests/RegistrationPage.test.jsx

- redesign tpa hint button accourding to new design
VAN-411
**Before**
**After**

Redesign tpa hint

---

public/index.html

Adding another check for optimizely url to cater stage experiments.

update optimizely script

---

src/register/RegistrationPage.jsx

Adding code to track custom events in Optimizely. The event `user_registered_successfully` will be tracked and associated with the current visitor.
Ticket: https://openedx.atlassian.net/browse/VAN-487

Fire optimizely event

---

src/_style.scss
src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/messages.js
src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
src/login/LoginFailure.jsx
src/login/LoginPage.jsx
src/login/data/service.js
src/login/messages.jsx
src/login/tests/LoginFailure.test.jsx
src/login/tests/LoginPage.test.jsx
src/register/RegistrationPage.jsx

Add the info mailto link to reset password form.
https://openedx.atlassian.net/browse/VAN-438
After shipping this change to staging and production environment, a user can see the info mail link on reset password page.

add mailto info link

---

src/index.jsx

Add info mail address to envs.

add info mail to config

---

src/data/constants.js

Add edx as an authorized domain in the service providers.
VAN-507

add edx as a valid service provider

---

src/common-components/RedirectLogistration.jsx
src/welcome/WelcomePage.jsx

Redirect ot finish auth URL if present upon clicking submit or skip on welcome page.

fix: welcome page redirection

---

src/data/utils/cookies.js
src/data/utils/index.js
src/register/RegistrationPage.jsx

Set returning user cookie to measure exit rate for A/B test.

feat: set returning user cookie

---

src/register/RegistrationPage.jsx

- Check password validation on frontend.
- Call backend validations only when frontend validations succeed. 
VAN-520

Fix password validation

---

src/_style.scss

fix: logo size

---

src/_style.scss
src/forgot-password/messages.js
src/forgot-password/tests/ForgotPasswordPage.test.jsx
src/login/tests/LoginPage.test.jsx
src/register/RegistrationPage.jsx
src/reset-password/ResetPasswordPage.jsx
src/reset-password/tests/ResetPasswordPage.test.jsx

context:
- updated password reset error message
- on field focus, both field error were being dismissed.
- updated button submission state (no text, show spinner only)
- Fix few tests that were throwing console errors
Ticket: https://openedx.atlassian.net/browse/VAN-451

reset password redesign bugs

---

package-lock.json
package.json
src/common-components/AlertDismissible.jsx
src/common-components/tests/__snapshots__/ThirdPartyAuthAlert.test.jsx.snap
src/forgot-password/ForgotPasswordAlert.jsx
src/login/LoginFailure.jsx
src/login/tests/AccountActivationMessage.test.jsx
src/register/RegistrationFailure.jsx
src/reset-password/ResetPasswordFailure.jsx

alert styling updated

---

src/register/RegistrationPage.jsx
src/welcome/WelcomePage.jsx

Also, added a new optimizely event to capture total registrations.

feat: send page event for welcome page

---

src/common-components/PasswordField.jsx
src/common-components/messages.jsx
src/register/tests/RegistrationPage.test.jsx
src/reset-password/tests/ResetPasswordPage.test.jsx

Password show and hide icon replaced with paragon icon

---

package-lock.json
package.json
src/_style.scss
src/common-components/FormGroup.jsx
src/register/CountryDropdown.jsx
src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

Add searchable dropdown field to make the UI complaint with the suggestions.
https://openedx.atlassian.net/browse/VAN-498
After shipping this change to staging and production environment, a user can experience the new experience on dropdown fields.

Add searchable dropdown

---

src/register/CountryDropdown.jsx

Fix typo for Focus In

---

src/_style.scss
src/register/CountryDropdown.jsx

fix: design and country dropdown issues

---

src/_style.scss
src/common-components/Logistration.jsx

- Logistration Tabs behavior and styles fix by using Paragon Tab component.
VAN-554

fix: Logistration tabs behavior

---

package-lock.json
package.json
src/login/tests/LoginPage.test.jsx
src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

1. updated paragon package to the latest version
2. removed .small from legal text and replaced it with .micro
3. fixed the spinner to be center aligned on buttons during pending state
https://openedx.atlassian.net/browse/VAN-593
https://openedx.atlassian.net/browse/VAN-546

fix: update class for legal text

---

src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

Changed experiment name to verify conversion rate anomaly noticed during third test run.

refactor: change experiment name

---

src/register/RegistrationPage.jsx

Fix unrelated suggestions on email input field.
VAN-599

fix unrelated suggestions

---

src/_style.scss
src/common-components/PasswordField.jsx
src/forgot-password/ForgotPasswordAlert.jsx
src/register/RegistrationPage.jsx

ui issues fixed

---

package-lock.json
package.json
src/register/RegistrationPage.jsx
src/register/messages.jsx

- Added help text for full name field on registration page (see https://openedx.atlassian.net/browse/VAN-542)
- Updated paragon package to incorporate `.micro` class line height changes (see https://openedx.atlassian.net/browse/VAN-546)
- Added `.text-muted` to disclaimer text after feedback from UX team

add help text for fullname field

---

src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

Changed Optimizely experiment.

temp: Optimizely experiment

---

src/_style.scss
src/common-components/PasswordField.jsx
src/forgot-password/ForgotPasswordAlert.jsx

password icon size fixed

---

src/_style.scss
src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/tests/ForgotPasswordPage.test.jsx

- Using paragon Tab component in Logistration and ForgotPasswordPage components for redirection.
VAN-554
**Before**
**After**

fix: Redirection Tab component

---

src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx
src/welcome/WelcomePage.jsx

temp: added new Optimizely exp/events

---

src/redesign/_style.scss
src/redesign/common-components/Logistration.jsx
src/redesign/forgot-password/ForgotPasswordPage.jsx
src/redesign/reset-password/ResetPasswordPage.jsx
src/redesign/reset-password/tests/ResetPasswordPage.test.jsx

- Paragon Tab component is using for redirection instead Link.
VAN-554

fix: Redirection using Tab component

---

src/redesign/_style.scss
src/redesign/register/CountryDropdown.jsx

Fix anomalies like:
1. spacing between the borderline and dropdown
2. icon alignment
3. Country list on icon click.
VAN-559

fix anomalies in dropdown

---

src/redesign/_style.scss
src/redesign/register/CountryDropdown.jsx

fix a11y related concerns in country dropdown.
VAN-559

fix a11y in dropdown

---

src/legacy/register/RegistrationPage.jsx
src/redesign/register/RegistrationPage.jsx

Added for the launch experiment to calculate the average time per user per variation.

temp: send total register time to Optimizely

---

src/redesign/common-components/BaseComponent.jsx
src/redesign/data/utils/dataUtils.js
src/redesign/index.jsx
src/redesign/login/LoginPage.jsx
src/redesign/reset-password/ResetPasswordPage.jsx

Added `?theme=redesign` query param to segregate recordings, heatmaps in HotJar.

temp: add theme query param for redesign

---

src/redesign/_style.scss
src/redesign/register/RegistrationPage.jsx

Fix the top-margin on the top of the content on registration page.
VAN-616

fix-content-for-small-screen

---

package-lock.json
package.json
src/redesign/_style.scss
src/redesign/register/RegistrationPage.jsx

- email suggestion style fix according to figma style.
VAN-601

fix: Email suggestion styles

---

src/redesign/_style.scss

fix: username suggestion chip styles

---

package-lock.json
package.json
src/redesign/_style.scss
src/redesign/register/RegistrationPage.jsx

- update alert style in Paragon.
- update Paragon version in this repo.
VAN-558

chore: update paragon version

---

src/redesign/login/LoginPage.jsx
src/redesign/login/messages.jsx
src/redesign/login/tests/LoginPage.test.jsx

Rephrase Username or email field error text.
VAN-638

rephrase error text

---

package-lock.json
package.json

Upgrade paragon version to latest

upgrade paragon version

---

src/redesign/_style.scss

- update alert heading color and icon size in paragon.
- update paragon version in this repo.
VAN-558

fix: alert heading style

---

src/redesign/_style.scss

- fix page jump when switching between login and register tabs due to scrollbar.
**After fix**
https://user-images.githubusercontent.com/78487564/125078399-c4d9cd80-e0db-11eb-8e49-d4acd0054196.mp4
VAN-574

fix: page jump switching b/w logon & register

---

src/redesign/register/RegistrationPage.jsx

A/B release progressive profiling welcome page. Changes include:
- added a cookie to check for exit rate
- redirect to welcome page only when config and experiment name match
[VAN-676](https://openedx.atlassian.net/browse/VAN-676)

chore: add optimizely experiment

---

src/register/RegistrationPage.jsx
src/welcome/WelcomePage.jsx

An optimizely event that is fired when any button i.e `Submit` or `Skip for now`, is clicked.

chore: add welcome page optimizely event

---

src/register/RegistrationPage.jsx
src/welcome/WelcomePage.jsx

Currently welcome page is behind an optimizely experiment flag. Removing it will enable it for all users.

refactor: enable welcome page for all users

---

src/common-components/FormGroup.jsx
src/register/CountryDropdown.jsx
src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

- fix to stop auto complete country field when address is saved in browser.
**Results**
https://user-images.githubusercontent.com/78487564/128874198-beda6da3-53ed-4d5a-93f3-1df61d7db2ee.mp4
VAN-671

fix: stop auto complete country

---

package-lock.json
package.json

Reverts edx/frontend-app-authn#417

Revert "chore: upgrade frontend-platform version to 1.12.1"

---

src/welcome/WelcomePage.jsx
src/welcome/tests/WelcomePage.test.jsx

chore: send analytic events for Welcome page

---

src/_style.scss
src/base-component/DiscountBanner.jsx
src/base-component/LargeLeftLayout.jsx
src/base-component/MediumLayout.jsx
src/base-component/SideDiscountBanner.jsx
src/base-component/SmallLayout.jsx
src/base-component/messages.jsx

Fixed some Design issues and added a toast on clicking copy.

fix: design issue in discount experiment

---

src/_style.scss
src/common-components/PasswordField.jsx
src/common-components/tests/FormField.test.jsx

Fix these small tickets in this PR:
[VAN-570](https://openedx.atlassian.net/browse/VAN-570)
[VAN-569](https://openedx.atlassian.net/browse/VAN-569)
[VAN-562](https://openedx.atlassian.net/browse/VAN-562)

Fix: Some design issue on register page.

---

src/register/messages.jsx

update error msg for username

---

src/common-components/Logistration.jsx
src/common-components/messages.jsx
src/register/RegistrationPage.jsx
src/register/messages.jsx

|Language|Variation 1|Variation 2|
|----|-----|----|
English|<img width="1916" alt="Screenshot 2021-11-09 at 3 05 35 PM" src="https://user-images.githubusercontent.com/40633976/140906674-5a94d412-d7c9-422d-ab2e-60a5e5f67138.png">|<img width="1916" alt="Screenshot 2021-11-09 at 3 05 53 PM" src="https://user-images.githubusercontent.com/40633976/140906779-e9bb6169-e345-4e30-8b27-d807c305eda9.png">
Spanish|<img width="1916" alt="Screenshot 2021-11-09 at 3 14 00 PM" src="https://user-images.githubusercontent.com/40633976/140906686-a9aa513a-2719-462c-8bd9-95d03b61c913.png">|<img width="1916" alt="Screenshot 2021-11-09 at 3 13 47 PM" src="https://user-images.githubusercontent.com/40633976/140906850-4f4baf60-b617-4d9c-a195-1d09d9e93d0d.png">
Details about the experiment can be found on …

feat: add rename register experiment details

---

src/register/RegistrationPage.jsx

Enable full name-based username suggestions and remove experiment-related changes.

feat: enable full name based username suggestions

---

src/reset-password/ResetPasswordPage.jsx
src/reset-password/data/service.js

[VAN-666](https://openedx.atlassian.net/browse/VAN-666)

feat: VAN-666 - Reject new password that is detected as vulnerable

---

src/common-components/Logistration.jsx

do options call on page load time for login api to reduce request response time.
VAN-715

perf: csrf token call

---

src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

Updated event names to reflect level of hierarchy in the events. The updates done are based on this document here: https://openedx.atlassian.net/l/c/fHudu1EM
[VAN-830](https://openedx.atlassian.net/browse/VAN-830)

feat: update save_for_later event name

---

src/register/RegistrationPage.jsx
src/register/messages.jsx

In order to decrease time in between when user clicks the `Create account` button and successfully get registered;
- removed validation call from the submission function
- ~~did the OPTIONS call at the time of page load~~
[VAN-711](https://openedx.atlassian.net/browse/VAN-711)

feat: improve register response time

---

src/_style.scss
src/common-components/Logistration.jsx
src/common-components/messages.jsx
src/data/constants.js
src/register/RegistrationPage.jsx
src/register/messages.jsx

https://openedx.atlassian.net/browse/VAN-876

feat: VAN-876 - Rename register experiment with improved metrics

---

src/register/RegistrationPage.jsx

Fixed the registration page's form loading button width issue

fix: fixed the className condition to apply styling properly

---

src/_style.scss
src/register/RegistrationPage.jsx
src/register/messages.jsx
src/register/tests/RegistrationPage.test.jsx

Making the experiment changes (VAN-704) permanent in the codebase.
Changed the Register form button text to 'Create an account for free'
|Language|Mobile|Desktop|
|----|---|---|
|English|![Screenshot 2022-04-26 at 12 39 47 PM](https://user-images.githubusercontent.com/14912524/165254732-ea946a1b-86a7-4bae-8c3a-0036b7fc3a1f.png)|![Screenshot 2022-04-26 at 12 39 32 PM](https://user-images.githubusercontent.com/14912524/165254781-1080da68-3871-4305-b6f6-fd9af2729df9.png)
|Spanish|![Screenshot 2022-04-26 at 1 11 26 PM](https://user-images.githubusercontent.com/14912524/165255036-23cb3e74-225c-4f9d-94dc-3c3365887cda.png)|![Screenshot 2022-04-26 at 1 11 15 PM](https://user-images.githubusercontent.com/14912524/165255086-9149e138-1bf0-4280-944f-04453a8e4e55.png)|

feat: VAN-935 - Launch rename register

---

src/common-components/FormGroup.jsx
src/common-components/PasswordField.jsx

Added aria-Invalid="true" to error-state fields in /login, /register and /reset pages
[VAN-548](https://2u-internal.atlassian.net/browse/VAN-548)

fix: Add aria-Invalid="true" to error-state fields

---

src/base-component/LargeLeftLayout.jsx

|Before|After|
|------|------|
Ticket: **https://2u-internal.atlassian.net/browse/VAN-500**

fix: update yellow arc position

---

src/forgot-password/ForgotPasswordPage.jsx
src/login/LoginPage.jsx
src/register/RegistrationPage.jsx
src/reset-password/ResetPasswordPage.jsx
src/welcome/WelcomePage.jsx

Add Names & IDs to Authentication Forms.
[VAN-948](https://openedx.atlassian.net/browse/VAN-948)

chore:[VAN-948] Add name and id to the forms.

---

src/_style.scss
src/common-components/data/actions.js
src/common-components/data/reducers.js
src/common-components/data/sagas.js
src/common-components/data/selectors.js
src/common-components/data/service.js
src/common-components/data/tests/sagas.test.js
src/field-renderer/FieldRenderer.jsx
src/field-renderer/tests/FieldRenderer.test.jsx
src/index.jsx
src/register/CountryDropdown.jsx
src/register/HonorCode.jsx
src/register/RegistrationPage.jsx
src/register/TermsOfService.jsx
src/register/data/constants.js
src/register/data/reducers.js
src/register/data/sagas.js
src/register/data/tests/reducers.test.js
src/register/messages.jsx
src/register/tests/HonorCode.test.jsx
src/register/tests/RegistrationPage.test.jsx
src/register/tests/TermsOfService.test.jsx

Fields can now be added dynamically to the registration page. These changes are currently behind the `ENABLE_DYNAMIC_REGISTRATION_FIELDS `. 
Ticket: https://openedx.atlassian.net/browse/VAN-838

feat: add required field support

---

openedx.yaml

We would now like to make this repo available as part of the Nutmeg release, even if it's not part of the default experience.

build: this MFE should be included in the open releases

---

src/MainApp.jsx
src/common-components/RedirectLogistration.jsx
src/common-components/data/actions.js
src/common-components/data/reducers.js
src/common-components/data/sagas.js
src/common-components/data/selectors.js
src/common-components/data/service.js
src/common-components/data/tests/sagas.test.js
src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx
src/welcome/ProgressiveProfiling.jsx
src/welcome/data/actions.js
src/welcome/data/reducers.js
src/welcome/data/sagas.js
src/welcome/data/service.js
src/welcome/tests/ProgressiveProfiling.test.jsx

Remove  ***Optional Field*** API call from the progressive profiling page. Use a `common component` to get the call. from api.
Ticket: https://2u-internal.atlassian.net/browse/VAN-953

feat: [VAN-953] update progressive profiling according to MFE API

---

src/_style.scss
src/data/utils/dataUtils.js
src/data/utils/dataUtils.test.js
src/data/utils/index.js
src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/messages.js
src/login/LoginFailure.jsx
src/login/tests/LoginFailure.test.jsx
src/login/tests/LoginPage.test.jsx
src/reset-password/ResetPasswordPage.jsx

- removed few unused classes
- updated login page to rely on error messages generated from the frontend only.
[VAN-138](https://2u-internal.atlassian.net/browse/VAN-138)

feat: update logistration pages

---

src/common-components/PasswordField.jsx
src/login/LoginPage.jsx
src/register/RegistrationPage.jsx

Turned auto-complete off for username and password field on registration form.
[VAN-1028](https://2u-internal.atlassian.net/browse/VAN-1028)

feat: turn auto-complete off

---

.env.development
src/index.jsx
src/register/RegistrationPage.jsx
src/register/messages.jsx
src/register/tests/TermsOfService.test.jsx
src/welcome/ProgressiveProfiling.jsx

Update the error message both backend and frontend to make it consistent and also makes some fixes.
[VAN-976](https://2u-internal.atlassian.net/browse/VAN-976)

fix: Small changes in extended profile

---

src/_style.scss

|Before|After|
|----|-----|
Ticket: https://2u-internal.atlassian.net/browse/VAN-1022

fix: update tooltip size for smaller screens

---

src/common-components/PasswordField.jsx
src/login/LoginPage.jsx

Reverts: https://github.com/openedx/frontend-app-authn/pull/605

fix: turn autocomplete on

---

src/register/RegistrationPage.jsx

Turned autoComplete on for username field as well

fix: remove autocomplete from username field

---

src/register/CountryDropdown.jsx

This PR fixes the country field's error messages on the field's focused state.

fix: VAN-1025 - Handle validation error on field focus

---

src/register/RegistrationPage.jsx

fix: [VAN-1058] Fix the checkbox placement UX issue.

---

src/register/RegistrationPage.jsx
src/register/data/constants.js
src/register/data/selectors.js
src/register/tests/RegistrationPage.test.jsx

Backend validation error for dynamic fields was being received in response but was being displayed.
[VAN-1037](https://2u-internal.atlassian.net/browse/VAN-1037)

fix: Backend validations not showing on frontend for dynamic fields 

---

src/login/LoginPage.jsx
src/login/tests/LoginPage.test.jsx

- sign-in header on login page only show when social authn is active.
VAN-1055

fix: sign-in header on login page

---

package-lock.json
package.json
src/data/constants.js
src/field-renderer/FieldRenderer.jsx
src/forgot-password/ForgotPasswordAlert.jsx
src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/messages.js
src/sass/_style.scss

- Remove Formik
- Updated ForgotPasswordAlert to use constants
- Fixed design issues
Ticket: https://2u-internal.atlassian.net/browse/VAN-1056

feat: VAN-1056 - remove formik

---

src/field-renderer/FieldRenderer.jsx

Ticket: https://2u-internal.atlassian.net/browse/VAN-1063

fix: fix console warnings while running tests [VAN-1063]

---

src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

|Before|After|
|----|-------|
Ticket: https://2u-internal.atlassian.net/browse/VAN-1087

fix: username prefixed with space character

---

src/register/data/reducers.js

Ticket: https://2u-internal.atlassian.net/browse/VAN-1090

fix: VAN-1090 - Handled country field's errors on empty field

---

src/login/LoginFailure.jsx
src/login/data/constants.js
src/login/messages.jsx
src/login/tests/LoginFailure.test.jsx

display error message on login page if staff user try to login through password.
VAN-1082

fix: display error message

---

src/common-components/EnterpriseSSO.jsx
src/common-components/InstitutionLogistration.jsx
src/common-components/Logistration.jsx
src/common-components/ThirdPartyAuthAlert.jsx
src/common-components/data/reducers.js
src/common-components/data/selectors.js
src/common-components/messages.jsx
src/login/LoginPage.jsx
src/register/RegistrationPage.jsx
src/register/ThirdPartyAuth.jsx
src/register/data/actions.js
src/register/data/reducers.js
src/register/messages.jsx

The PR has the following changes: 
- Add code to handle third-party auth registration and institution registration flows
- Add error handling
- Password field is not shown on the form when a user authenticates via a TPA link
- Handle state persistence when tabs are switched

feat: Add tpa auth and institution login

---

src/base-component/LargeLayout.jsx
src/base-component/MediumLayout.jsx
src/base-component/SmallLayout.jsx

https://2u-internal.atlassian.net/browse/VAN-1099
|BEFORE | AFTER |
|------|--------|

fix: Add yellow slanted line back for edX only

---

src/register/CountryDropdown.jsx
src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

Fix Error selecting country while creating account on translations of different language.

[VAN-1135]: Fix selecting country error while creating account

---

src/login/LoginPage.jsx
src/register/RegistrationPage.jsx

The segment page event is not sent when a user visits the login register page for the first time.
This is an intermittent issue.
[VAN-1160](https://2u-internal.atlassian.net/browse/VAN-1160)

fix: segment page event not sent

---

src/common-components/PasswordField.jsx
src/forgot-password/ForgotPasswordPage.jsx
src/login/LoginPage.jsx
src/register/CountryDropdown.jsx
src/register/RegistrationPage.jsx
src/register/UsernameField.jsx

All input fields for /login, /register, and /reset include autocomplete attribute.

fix: [VAN-544] Add autocomplete attribute fir input fields.

---

README.rst

fix: remove extra badges

---

README.rst
docs/how_tos/enable_social_auth.rst

added enable social auth locally documentation

feat: add enable social auth locally docs

---

src/reset-password/data/sagas.js
src/reset-password/data/tests/sagas.test.js

Include a description of your changes here, along with a link to any relevant Jira tickets and/or Github issues.
|Before|After|

fix: add token invalid case in reset password.

---

src/register/data/utils.js
src/register/tests/RegistrationPage.test.jsx

Include a description of your changes here, along with a link to any relevant Jira tickets and/or Github issues.
|Before|After|

fix: Fix selecting country error while applying translations

---

catalog-info.yaml

Add catalog-info.yaml file. Added file according to this Doc: https://docs.openedx.org/en/latest/developers/how-tos/add-a-catalog-file.html

feat: make authn-app compliant with OEP-55

---

src/common-components/tests/Logistration.test.jsx
src/field-renderer/tests/FieldRenderer.test.jsx
src/forgot-password/tests/ForgotPasswordPage.test.jsx
src/login/messages.jsx
src/login/tests/LoginFailure.test.jsx
src/login/tests/LoginPage.test.jsx
src/register/messages.jsx
src/register/tests/HonorCode.test.jsx
src/register/tests/RegistrationPage.test.jsx
src/register/tests/TermsOfService.test.jsx
src/welcome/tests/ProgressiveProfiling.test.jsx

Remove edX keyword from tests
Updated tests

fix: remove edx keyword from tests

---

src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/tests/ForgotPasswordPage.test.jsx

- We are creating this PR for stage-frontend-app-authn-e2e-tests gocd pipeline testing.
- We will revert these changes after testing.
VAN-989

test: for stage-frontend-app-authn-e2e-tests job testing

---

src/forgot-password/ForgotPasswordPage.jsx
src/forgot-password/tests/ForgotPasswordPage.test.jsx

This reverts commit 059d79302d3e5458dcf6b8b3d04014c2d0f7f72c.

Revert "test: for stage-frontend-app-authn-e2e-tests job testing (#705)"

---

README.rst

This PR updates the README according to  OEP-55 and OEP-19 guidelines.

docs: Update README

---

src/register/RegistrationPage.jsx

Fix the error banner position.
|Before|After|
|   ![register](https://user-images.githubusercontent.com/7627421/208064714-35b2c70a-e9b4-4a68-b4ef-bcf9d509cc92.png)   |   <img width="518" alt="Screenshot 2022-12-15 at 7 47 34 PM" src="https://user-images.githubusercontent.com/7627421/208064502-b462ed00-53e1-47e3-b579-e14523a0ae2a.png">   |

fix: fix error banner position on registration page.

---

src/common-components/RedirectLogistration.jsx
src/common-components/data/reducers.js
src/common-components/data/tests/reducers.test.js
src/progressive-profiling/ProgressiveProfiling.jsx
src/register/RegistrationPage.jsx

frontend-platform's `ensureAuthenticatedUser` was throwing exceptions incase of the unauthenticated user along with redirecting to the login page. This PR passes that exception.
[VAN-1224](https://2u-internal.atlassian.net/browse/VAN-1224)

fix: uncaught exception on progressive profiling

---

src/common-components/RedirectLogistration.jsx
src/common-components/data/reducers.js
src/common-components/data/tests/reducer.test.jsx
src/progressive-profiling/ProgressiveProfiling.jsx
src/register/RegistrationPage.jsx

Description
frontend-platform's ensureAuthenticatedUser was throwing exceptions incase of the unauthenticated user along with redirecting to the login page. This PR passes that exception.
[VAN-1224](https://2u-internal.atlassian.net/browse/VAN-1224)

fix: exception at progressive profiling page

---

src/register/RegistrationPage.jsx

Fire GTM event used for integration with impact.com

feat: add GTM fired for integration with impact.com

---

src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

Added logs to debug the undefined message being sent to intl.
Ticket: https://2u-internal.atlassian.net/browse/VAN-1232
Updated tests

feat: add debugging logs

---

src/register/RegistrationPage.jsx
src/register/tests/RegistrationPage.test.jsx

`pipelineUserDetails` has extra fields like `firstName` and `lastName` which were causing issue in isFormValid functionality. 
**Error details:** On NewRelic this new error has started appearing and looks like it happened after the refactor code was merged: `An undefined message was supplied to intl.formatMessage`.
The issue is in the registration page.

feat: pick required fields from tpa context

---

src/data/constants.js
src/progressive-profiling/tests/ProgressiveProfiling.test.jsx
src/recommendations/RecommendationsList.jsx
src/recommendations/RecommendationsPage.jsx
src/recommendations/data/constants.js
src/recommendations/tests/RecommendationsPage.test.jsx
src/recommendations/tests/constants.js

Add tests for the recommendations functionality. Tests added for
- Progressive profiling page: This is where we decide whether to add recommendations or not
- Recommendations page tests
-

zamir/van 1295/add tests for recommender

---

package-lock.json
package.json
src/data/optimizely.js
src/progressive-profiling/ProgressiveProfiling.jsx
src/recommendations/RecommendationCard.jsx
src/recommendations/optimizelyExperiment.js

VAN-1330
This PR converts post-registration recommendations optimizely web experiment to optimizely full stack experiment.
Tested locally with optimizely full stack logs

feat: shift recommendations experiment to optimizely full stack

---

src/progressive-profiling/ProgressiveProfiling.jsx
src/progressive-profiling/tests/ProgressiveProfiling.test.jsx

Reverts openedx/frontend-app-authn#774

Revert "fix: make identify call to pass missing user_id"

---

.github/pull_request_template.md

Update pull request template to include jira ticket

fix: update pull request template

---

.github/workflows/autoupdate.yml

Description
add workflow for autoupdate OSPRs 
Related to: https://2u-internal.atlassian.net/browse/VAN-1349

feat: create autoupdate workflow

---

src/common-components/RedirectLogistration.jsx
src/common-components/SocialAuthProviders.jsx
src/common-components/tests/Logistration.test.jsx
src/common-components/tests/SocialAuthProviders.test.jsx
src/register/RegistrationPage.jsx
src/register/data/utils.js
src/register/tests/RegistrationPage.test.jsx

[VAN-1318](https://2u-internal.atlassian.net/browse/VAN-1318)
This PR adds support for the skip_registeration_form setting for SSO which means that the user will not be shown the registration form if the user is registering through SSO and skip_registeration_form is enabled.
Tested Locally

feat: add support for skip_registration_form setting for SSO

---

src/recommendations/RecommendationCard.jsx
src/recommendations/tests/RecommendationsPage.test.jsx

Description
Need to update test cases for recommendations page and recommendation card
Its been tested locally
Related to: https://2u-internal.atlassian.net/browse/VAN-1351

fix: improve test coverage of recommendations

---

src/progressive-profiling/ProgressiveProfiling.jsx

Fix the Design issue with progressive profiling page  on medium and small screens
[VAN-1355](https://2u-internal.atlassian.net/browse/VAN-1355)
|Before|After|
|<img width="749" alt="Screenshot 2023-03-31 at 2 21 00 PM" src="https://user-images.githubusercontent.com/7627421/229717535-983722e4-d72c-4783-9f1c-f625d77d7aa4.png">|<img width="639" alt="Screenshot 2023-04-04 at 12 21 11 PM" src="https://user-images.githubusercontent.com/7627421/229717900-cd4f8917-26ab-4545-ba01-0cac22f46d75.png">|
|<img width="292" alt="Screenshot 2023-03-31 at 2 21 19 PM" src="https://user-images.githubusercontent.com/7627421/229718026-61060224-4bad-4218-893c-230d3d5e6071.png">|<img width="318" alt="Screenshot 2023-04-04 at 12 15 44 PM" …

fix: fix design issue on progressive profiling page

---

src/common-components/ThirdPartyAuthAlert.jsx
src/common-components/tests/__snapshots__/ThirdPartyAuthAlert.test.jsx.snap

Description
FIX margin issue for SSO banner on login page.
This is tested locally we need to login with email which is not registered before
Related to: https://2u-internal.atlassian.net/browse/VAN-1353

fix: margin issue for sso baner

---

.github/workflows/autoupdate-pull-request.yml

Description
Trigger autoupdate workflow when autoupdate label is added into PR
This would be tested on actually PR
Related to: https://2u-internal.atlassian.net/browse/VAN-1349

fix: add new flag in autoupdate action

---

.github/workflows/autoupdate-pull-request.yml

Update Github token in autoupdate workflow
Related: https://2u-internal.atlassian.net/browse/VAN-1349

fix: update github token

---

Makefile

Added the flag back in pull_translation command that was removed in https://github.com/openedx/frontend-app-authn/pull/747. 
See https://github.com/openedx/frontend-app-authn/pull/682 for more details

fix: update pull translation command

---

src/common-components/data/service.js

Reverts openedx/frontend-app-authn#835

Revert "fix: change keys to camelCase for mfe_context response"

---

src/register/data/tests/reducers.test.js
src/register/tests/RegistrationPage.test.jsx

Description
Increase test coverage of registration flow
VAN-1368
Its been test locally
Related : https://2u-internal.atlassian.net/browse/VAN-1368

fix: registration test coverage

---

src/reset-password/data/constants.js
src/reset-password/tests/ResetPasswordPage.test.jsx

Description
Improve the code coverage of reset-password component
Its been tested locally 
Related to: https://2u-internal.atlassian.net/browse/VAN-1369

fix: reset-password code coverage

---

src/common-components/data/service.js

We needed to resolve the issue that has been identified with PR #835

fix: change keys to camelCase for mfe_context response (PR# 835)

---

src/register/ConfigurableRegistrationForm.jsx
src/register/data/constants.js
src/register/data/utils.js
src/register/registrationFields/CountryField.jsx
src/register/tests/RegistrationPage.test.jsx
src/sass/_registration.scss

VAN-1415
use paragon Autosuggest field for country field
[VAN-1415](https://2u-internal.atlassian.net/browse/VAN-1415)
Locally

refactor: use paragon Autosuggest field for country field

---

src/common-components/ThirdPartyAuth.jsx
src/common-components/messages.jsx
src/login/LoginFailure.jsx
src/login/LoginPage.jsx
src/login/data/actions.js
src/login/messages.jsx
src/register/RegistrationPage.jsx
src/register/messages.jsx

Refactored the following flows for login functionality:
1. Institution login
2. SSO login
3. TPA hint
Related to: [VAN-1391](https://2u-internal.atlassian.net/browse/VAN-1391)

refactor: refactor social auth, tpahint and institution login

---

src/recommendations/RecommendationsPage.jsx
src/recommendations/tests/RecommendationsPage.test.jsx
src/reset-password/ResetPasswordPage.jsx
src/sass/_reset_password.scss
src/sass/_style.scss

* Implemented BEM convention for reset password page
* Moved the reset password custom classes into separate file
It's related to: https://2u-internal.atlassian.net/browse/VAN-142
It's has been tested locally

refactor: BEM convention for reset password

---

src/common-components/EnterpriseSSO.jsx
src/common-components/FormGroup.jsx
src/common-components/InstitutionLogistration.jsx
src/common-components/PasswordField.jsx
src/common-components/SocialAuthProviders.jsx
src/common-components/tests/__snapshots__/SocialAuthProviders.test.jsx.snap
src/progressive-profiling/ProgressiveProfiling.jsx
src/progressive-profiling/tests/ProgressiveProfiling.test.jsx
src/recommendations/RecommendationCard.jsx
src/recommendations/RecommendationsList.jsx
src/sass/_login_page.scss
src/sass/_progressive_profiling_page.scss
src/sass/_recommendations_page.scss
src/sass/_style.scss

Description:
1. Implemented BEM convention for common components
2. Moved the classes which were related to common components only few lefts which were used in some other components
it's been tested locally.
Its related to: https://2u-internal.atlassian.net/browse/VAN-1425

refactor: BEM convention for common components

---

src/forgot-password/ForgotPasswordPage.jsx
src/register/ConfigurableRegistrationForm.jsx
src/register/RegistrationPage.jsx
src/register/registrationFields/EmailField.jsx
src/register/registrationFields/HonorCode.jsx
src/register/registrationFields/TermsOfService.jsx
src/register/registrationFields/UsernameField.jsx
src/register/tests/RegistrationPage.test.jsx
src/sass/_forgot_password.scss
src/sass/_registration.scss
src/sass/_style.scss

* Implemented BEM convention for register and forgot password page 
* Moved the custom classes into a separate files
Tickets:
https://2u-internal.atlassian.net/browse/VAN-1421
https://2u-internal.atlassian.net/browse/VAN-1424
It has been tested locally

refactor: BEM convention for modules

---

src/sass/_registration.scss

Fix the design issue of the username field.

fix: fix design issue in user name suggestion field

---

src/common-components/tests/UnAuthOnlyRoute.test.jsx
src/field-renderer/tests/FieldRenderer.test.jsx
src/reset-password/tests/ResetPasswordPage.test.jsx

While running tests on Authn, there are a lot of [console errors](https://github.com/openedx/frontend-app-authn/actions/runs/5069032101/jobs/9102082371) in different components. This PR fixes the errors.
[VAN-1433](https://2u-internal.atlassian.net/browse/VAN-1433)
It has been tested locally and also no console error in this test [build](https://github.com/openedx/frontend-app-authn/actions/runs/5134342643/jobs/9238215732?pr=930)

fix: fix console errors on running test

---

src/data/constants.js
src/logistration/Logistration.jsx
src/logistration/Logistration.test.jsx
src/register/RegistrationPage.jsx
src/sass/_style.scss

Description:
In this we have changed the registration form on the basis of variant query param and hide the multiple things like registration button
I have tested it locally.
Its related to: 
https://2u-internal.atlassian.net/browse/VAN-1476
Screenshots

fix: change registration form for onramp

---

public/index.html

VAN-1475
This PR adds an iframe resizer script so that the iframe can be resized with the authn height on the iframe hosting site.
[VAN-1475](https://2u-internal.atlassian.net/browse/VAN-1475)

feat: add iframe resizer script

---

src/common-components/RedirectLogistration.jsx
src/common-components/UnAuthOnlyRoute.jsx
src/common-components/tests/UnAuthOnlyRoute.test.jsx
src/data/utils/dataUtils.js
src/logistration/Logistration.jsx
src/register/RegistrationPage.jsx

VAN-1482
allow the embedded experience to open the register page for authenticated users
[VAN-1482](https://2u-internal.atlassian.net/browse/VAN-1482)
|Before|After|

feat: allow embedded experience to open register page for authenticated users

---

src/data/constants.js
src/progressive-profiling/ProgressiveProfiling.jsx
src/progressive-profiling/tests/ProgressiveProfiling.test.jsx

Passing host property to registration and progressive profiling events to calculate on-ramp conversion rate.
VAN-1478

feat: registration conversion events

---

src/progressive-profiling/ProgressiveProfiling.jsx
src/progressive-profiling/tests/ProgressiveProfiling.test.jsx
src/register/RegistrationPage.jsx
src/register/data/actions.js
src/register/data/sagas.js
src/register/data/service.js
src/register/tests/RegistrationPage.test.jsx

This PR fires an identify call and register-event on registration success.
[VAN-1499](https://2u-internal.atlassian.net/browse/VAN-1499)

feat: fire identify call and register event

---

src/common-components/Zendesk.jsx

This Pr adds a check to hide Zendesk widget for embedded experience

fix: hide Zendesk widget for embedded experience

---

public/index.html

Adds optimizely web to authn
[VAN-1506](https://2u-internal.atlassian.net/browse/VAN-1506)

feat: add optimizely web to authn

---

src/base-container/components/image-layout/LargeLayout.jsx

Include a description of your changes here, along with a link to any relevant Jira tickets and/or Github issues.
|Before|After|

fix: height of image for larger layout

---

.env

Add configs to .env
[VAN-1506](https://2u-internal.atlassian.net/browse/VAN-1506)

chore: add configs to env file

---

src/base-container/data/constants.js
src/base-container/index.jsx

Fix glitch in rebrand experiment issue

fix: fix rebrand experiment issue

---

src/base-container/components/default-layout/DefaultLayout.test.jsx
src/base-container/tests/BaseContainer.test.jsx

Updated tests for base container.
Added/updated tests

feat: add base container tests

---

src/data/constants.js
src/progressive-profiling/ProgressiveProfiling.jsx
src/progressive-profiling/tests/ProgressiveProfiling.test.jsx
src/register/RegistrationPage.jsx
src/register/messages.jsx
src/register/tests/RegistrationPage.test.jsx

Register CTA label and authn redirection would be based on query params.
VAN-1535

feat: param based CTA and redirection

---

src/register/RegistrationPage.jsx
src/register/registrationFields/HonorCode.jsx
src/register/tests/HonorCode.test.jsx

VAN-1541, VAN-1551, VAN-1543
- Fix honor code and TOS styling
- Fix padding issue
[VAN-1541](https://2u-internal.atlassian.net/browse/VAN-1541)
[VAN-1551](https://2u-internal.atlassian.net/browse/VAN-1551)
[VAN-1543](https://2u-internal.atlassian.net/browse/VAN-1543)
locally

fix: fix accessibility issues in register embedded experience

---

src/common-components/data/reducers.js
src/progressive-profiling/ProgressiveProfiling.jsx
src/progressive-profiling/data/selectors.js
src/progressive-profiling/tests/ProgressiveProfiling.test.jsx

Register success redirection would be based on the next query params.
VAN-1535

feat: param based redirection

---

src/config/index.js
src/recommendations/RecommendationsPage.jsx
src/recommendations/tests/RecommendationsPage.test.jsx

Add popular and trending products to recommendations.
> Related [PR](https://github.com/edx/edx-internal/pull/8902)
[VAN-1565](https://2u-internal.atlassian.net/browse/VAN-1565)
Locally

fix: add popular and trending products lists

---

src/recommendations/ProductCard/Footer/index.jsx
src/recommendations/ProductCard/index.jsx
src/recommendations/data/constants.js
src/recommendations/data/utils.js
src/recommendations/messages.js
src/recommendations/tests/mockedData.js

Cleaning all organization specific code
locally

fix: clean recs code

---

src/progressive-profiling/ProgressiveProfiling.jsx
src/progressive-profiling/tests/ProgressiveProfiling.test.jsx
src/recommendations/ProductCard/BaseCard/index.jsx
src/recommendations/ProductCard/index.jsx
src/recommendations/RecommendationsPage.jsx
src/recommendations/data/constants.js
src/recommendations/track.js

Add segments events to track popular and trending recommendations.
[VAN-1569](https://2u-internal.atlassian.net/browse/VAN-1569)

feat: Add segments events

---

src/recommendations/ProductCard/hooks/useProducts.jsx
src/recommendations/RecommendationsPage.jsx
src/recommendations/data/tests/utils.test.jsx
src/recommendations/data/utils.js
src/recommendations/tests/RecommendationsPage.test.jsx
src/recommendations/tests/mockedData.js

Description:
Filter courses on the basis of location that is retrieved from user IP.
[VAN-1573](https://2u-internal.atlassian.net/browse/VAN-1573)

fix: add location resitriction for popular and trending courses

---

src/recommendations/ProductCard/hooks/useProducts.jsx
src/recommendations/RecommendationsPage.jsx

Description:
Fixed redirection issue
[VAN-1573](https://2u-internal.atlassian.net/browse/VAN-1573)

fix: redirection issue fix

---

src/recommendations/RecommendationsPage.jsx
src/recommendations/data/hooks/useProducts.jsx

moved hooks from product card dir to data dir
|Before|After|

refactor: refactor recs dir

---

src/register/registrationFields/UsernameField.jsx
src/sass/_registration.scss

The design of the username suggestions list has been updated in this PR based on the requirements mentioned in the ticket.
[VAN-1539](https://2u-internal.atlassian.net/browse/VAN-1539)
|Before|After|
|<img width="498" alt="Screenshot 2023-07-18 at 7 40 07 PM" src="https://github.com/openedx/frontend-app-authn/assets/32649010/88df710a-4409-434b-8a90-0c42337742b7">|<img width="498" alt="Screenshot 2023-07-18 at 7 23 02 PM" src="https://github.com/openedx/frontend-app-authn/assets/32649010/7753f78f-1c29-47c1-8ab0-ff7a13c372d5">|

fix: update username suggestions placement

---

src/data/utils/dataUtils.js

Reverts openedx/frontend-app-authn#1029

Revert "fix: special characters in redirect url getting decoded to space"

---

src/config/index.js
src/recommendations/ProductCard/BaseCard/index.jsx
src/recommendations/ProductCard/index.jsx
src/recommendations/RecommendationsList.jsx
src/recommendations/RecommendationsPage.jsx
src/recommendations/RecommendationsPageLayouts/LargeLayout.jsx
src/recommendations/RecommendationsPageLayouts/SmallLayout.jsx
src/recommendations/data/loadingCoursesPlaceholders.js
src/recommendations/messages.js
src/recommendations/tests/RecommendationsPage.test.jsx
src/sass/_recommendations_page.scss

VAN-1598
Update Post registration recommendations design according to [Figma](https://www.figma.com/file/nDYPI1KPAtzEOXAwESPlgW/Post-completion-recommendations?node-id=203%3A1169&mode=dev)
[VAN-1598](https://2u-internal.atlassian.net/browse/VAN-1598)
locally
|Screen size|Loading state|Recommendations|
|---------|----------------|------------------|
|X Large|<img width="1440" alt="Screenshot 2023-08-16 at 10 15 49 AM" src="https://github.com/openedx/frontend-app-authn/assets/52817156/ce52a2c4-e7de-464c-ba28-94aa8eab027e">|<img width="700" alt="Screenshot 2023-08-16 at 10 18 40 AM" src="https://github.com/openedx/frontend-app-authn/assets/52817156/3807865c-e839-49d4-935c-0a8aad76459f">|
|Large|<img width="500" alt="Screenshot 2023-08-16 at 10 17 03 AM" …

feat: update recommendations page design

---

src/register/registrationFields/UsernameField.jsx
src/register/tests/RegistrationPage.test.jsx
src/sass/_registration.scss

We fixed username suggestions placement on the register page for the small screen and now releasing these changes for openedX community. 
[VAN-1539](https://2u-internal.atlassian.net/browse/VAN-1539)
1. Go to register page.
2. Write your Full name and focus-out the field.
3. Suggestions will be displayed inside the username field.

Username suggestion placement issue on small screen

---

src/data/constants.js
src/register/EmbeddableRegistrationPage.jsx
src/register/tests/EmbeddableRegistrationPage.test.jsx

Description
Applied frontend validations on CTA click 
JIRA [VAN-1614](https://2u-internal.atlassian.net/browse/VAN-1614)

Ahtesham/van 1614/validations

---

src/logistration/Logistration.jsx

Forms data was not getting persisted due recent upgrade to react router v6 and its code changes.
[VAN-1621](https://2u-internal.atlassian.net/browse/VAN-1621)
|Before|After|

fix: forms data persistence issue

---

src/common-components/PasswordField.jsx
src/common-components/tests/FormField.test.jsx
src/reset-password/ResetPasswordPage.jsx
src/reset-password/tests/ResetPasswordPage.test.jsx

Reflected password field changes everywhere

fix: password validation with correct password value on icon blur

---

src/common-components/data/reducers.js
src/register/RegistrationPage.jsx
src/register/RegistrationPage.test.jsx

updated optional fields check based on updated response in https://github.com/openedx/edx-platform/pull/33183/files

fix: updated optional fields check based on updated response

---

src/recommendations/data/algoliaResultsParser.js
src/recommendations/data/tests/mockedData.js

Fixed event props not being passed for recommendations
BugBash bug
locally

fix: post registration recommendations eventing

---

src/recommendations/RecommendationsPage.jsx
src/recommendations/tests/RecommendationsPage.test.jsx

The skip button event gets cancelled due to redirection
BugBash bug

fix: recs skip btn event gets cancelled on redirection

---

src/config/index.js
src/register/components/ConfigurableRegistrationForm.test.jsx

Moved the value to internal configuration. Details are available here: https://github.com/edx/edx-internal/pull/9160
Related to [VAN-1624](https://2u-internal.atlassian.net/browse/VAN-1624)

feat: updated default value for USER_RETENTION_COOKIE_NAME

---

src/register/RegistrationFields/NameField/validator.js

Fixed name field validations
[VAN-1653](https://2u-internal.atlassian.net/browse/VAN-1653)
locally

fix: name field validations

---

package-lock.json
package.json

This PR resolves the `PUBLIC_PATH` configuration issue by upgrading frontend-platform from `v5.0.0` to `v5.5.4`.
|Before|After|

chore: bump frontend-platform (#1076)

---

src/register/data/utils.js

This is a backport of #1099 to `quince.master`.

[Quince backport] chore: bump frontend-platform (#1076)

---

src/base-component/AuthSmallLayout.jsx
src/base-component/MediumLayout.jsx
src/base-component/SmallLayout.jsx
src/sass/_base_component.scss

This pull request contains recommendations for fixing block indentation (make it decimal) and correct display of the header (z-index of the header) during adaptation.
PR to the open-release/quince.master branch:  https://github.com/openedx/frontend-app-authn/pull/1093
PR to the master branch: https://github.com/openedx/frontend-app-authn/pull/1094
|Before|After|
| ![image](https://github.com/openedx/frontend-app-authn/assets/17108583/8f8acaff-b538-4081-8f30-70f29f6b7dde) | ![image](https://github.com/openedx/frontend-app-authn/assets/17108583/6c3fe75b-305b-4d04-94c7-5b5fd47d0265) |
|Before|After|
| ![image](https://github.com/openedx/frontend-app-authn/assets/17108583/ed21aa26-4ddf-4715-8bb9-02ca791a5985) | …

fix: content centering and z-index position on adaptation

---

src/base-container/components/default-layout/MediumLayout.jsx
src/base-container/components/default-layout/SmallLayout.jsx

Fixed spacing in authn title in tablet version

fix: Fixed spacing in tablet version

---

src/register/RegistrationFields/CountryField/CountryField.jsx
src/register/RegistrationFields/CountryField/CountryField.test.jsx
src/register/RegistrationFields/CountryField/validator.js
src/register/components/ConfigurableRegistrationForm.test.jsx
src/register/data/utils.js
src/register/messages.jsx
src/sass/_registration.scss

Updated Country field text error when a user enters an invalid text in the box.
[VAN-1519](https://2u-internal.atlassian.net/browse/VAN-1519)
|Before|After|
|<img width="487" alt="Screenshot 2023-12-04 at 3 20 50 PM" src="https://github.com/openedx/frontend-app-authn/assets/7627421/37129406-e06d-4524-85df-7edf33819e10">|<img width="475" alt="Screenshot 2023-12-04 at 3 20 30 PM" src="https://github.com/openedx/frontend-app-authn/assets/7627421/06919a57-1c6c-4ae7-8f27-c381aa619ff9">|

fix: country field error is updated

---

src/common-components/tests/EmbeddedRegistrationRoute.test.jsx
src/common-components/tests/FormField.test.jsx
src/common-components/tests/UnAuthOnlyRoute.test.jsx

Migrate existing tests for the 'Common Components' functionalities from Enzyme to React Testing Library (RTL).
[VAN-1773](https://2u-internal.atlassian.net/browse/VAN-1773)

fix: Migrate common components tests to RTL

---

src/forgot-password/tests/ForgotPasswordPage.test.jsx
src/reset-password/tests/ResetPasswordPage.test.jsx

Migrate existing tests for the 'Forgot Password' and 'Reset Password' functionalities from Enzyme to React Testing Library (RTL).
[VAN-1771](https://2u-internal.atlassian.net/browse/VAN-1771)

fix: Migrate forgot password and reset password tests to RTL

---

src/login/tests/AccountActivationMessage.test.jsx
src/login/tests/ChangePasswordPrompt.test.jsx
src/login/tests/LoginFailure.test.jsx
src/login/tests/LoginPage.test.jsx

Migrate login unit tests to RTL
[VAN-1770](https://2u-internal.atlassian.net/browse/VAN-1770)
locally

refactor: convert login page tests from enzyme to react testing library

---

src/progressive-profiling/ProgressiveProfiling.jsx
src/progressive-profiling/tests/ProgressiveProfiling.test.jsx

Add “work experience” property to the welcome page event 
[VAN-1788](https://2u-internal.atlassian.net/browse/VAN-1788)

feat: add work experience property to the welcome page event

---

src/register/RegistrationPage.jsx
src/register/RegistrationPage.test.jsx
src/register/data/reducers.js
src/register/data/tests/reducers.test.js

Description: Check how many users update country on registration form after we auto populate it with IP. 
[VAN-1793](https://2u-internal.atlassian.net/browse/VAN-1793)

feat: fire event when user change the country field

---

src/register/RegistrationFields/NameField/NameField.jsx
src/register/RegistrationFields/NameField/NameField.test.jsx
src/register/RegistrationFields/NameField/validator.js
src/register/RegistrationPage.jsx
src/register/RegistrationPage.test.jsx
src/register/components/tests/ConfigurableRegistrationForm.test.jsx
src/register/data/reducers.js
src/register/data/tests/reducers.test.js
src/register/messages.jsx

Split full name to first name and last name and add to the registration form, both fields(first name and last name) are required.
[VAN-1802](https://2u-internal.atlassian.net/browse/VAN-1802)
Tested Locally

feat: split full name into first name and last name

---

src/register/RegistrationFields/CountryField/CountryField.jsx
src/register/RegistrationFields/CountryField/CountryField.test.jsx
src/register/components/ConfigurableRegistrationForm.jsx

Description: Country field is not populated when page load VAN-1795
[VAN-1795](https://2u-internal.atlassian.net/browse/VAN-1795)
it has been tested locally
After Fix:
https://github.com/openedx/frontend-app-authn/assets/12580995/6f4cf965-65b3-497e-87e6-120e8081b75b

fix: country field is not populated on page load

---

package-lock.json
package.json

Include a description of your changes here, along with a link to any relevant Jira tickets and/or Github issues.
|Before|After|

fix: updated frontend-build to fix sharp issue

---

src/register/RegistrationFields/NameField/NameField.test.jsx
src/register/RegistrationFields/NameField/validator.js
src/register/RegistrationPage.jsx
src/register/RegistrationPage.test.jsx
src/register/components/tests/ConfigurableRegistrationForm.test.jsx
src/register/data/reducers.js
src/register/data/tests/reducers.test.js
src/register/messages.jsx

TPA data is not auto-populated. This is because the keys in API don’t match the form field keys used in the auth code.
[VAN-1802](https://2u-internal.atlassian.net/browse/VAN-1802)
tested locally both on legacy and frontend authn

fix: fix issue of tpa data loading

---

src/base-container/components/welcome-page-layout/LargeLayout.jsx
src/base-container/components/welcome-page-layout/MediumLayout.jsx
src/base-container/components/welcome-page-layout/SmallLayout.jsx
src/base-container/components/welcome-page-layout/messages.js
src/base-container/index.jsx
src/progressive-profiling/ProgressiveProfiling.jsx

Replace username with name in welcome page component 
[VAN-1824](https://2u-internal.atlassian.net/browse/VAN-1824)
It has been tested locally
|After|
|-----|
|  ![image](https://github.com/openedx/frontend-app-authn/assets/12580995/36341810-e559-436c-b14e-6e4ea85809b8)|

fix: replace username with name in base component and on welcome page

---

src/progressive-profiling/ProgressiveProfiling.jsx

Remove username and bring in name field in case embedded registration 
[VAN-1824](https://2u-internal.atlassian.net/browse/VAN-1824)
|After|
|-----|
|![image](https://github.com/openedx/frontend-app-authn/assets/12580995/ed271f56-efc0-4e04-bcbe-939e174a66e3)|

fix: remove username and bring in name field for embedded case

---

src/register/data/optimizelyExperiment/useSimplifyRegistrationExperimentVariation.jsx

Temp PR for merging so that latest changes from edx-internal can be picked

fix: update comment

---

src/sass/_style.scss

Update custom SSO buttons to use brand colors 
[VAN-1838](https://2u-internal.atlassian.net/browse/VAN-1838)
It has been tested locally
|  Before  |After|
|-----|-----|
|![image](https://github.com/openedx/frontend-app-authn/assets/12580995/01cc693b-c5b1-4adf-8cae-b9d61283e614)| ![image](https://github.com/openedx/frontend-app-authn/assets/12580995/6d44b588-7430-4ab9-81dc-1e2d26ded7cc)|

fix: Update custom SSO buttons to use brand colors

---

src/register/RegistrationPage.jsx
src/register/data/optimizelyExperiment/helper.js
src/register/data/optimizelyExperiment/useSimplifyRegistrationExperimentVariation.jsx

Fix experiment initialization bug

fix: fix simplify registration experiment bugs

---

.github/pull_request_template.md
CODEOWNERS
README.rst
catalog-info.yaml
openedx.yaml

Updated code owners to use the correct vanguards group.

feat: update code owner information

---

src/register/RegistrationPage.jsx
src/register/data/optimizelyExperiment/track.js

Adding submit button click event in simplify registration experiment

feat: add submit btn click event

---

src/register/RegistrationPage.jsx

Removed password field extra validation
Locally
|Before|After|

fix: remove password field duplicate validation

---

src/base-container/data/constants.js
src/base-container/index.jsx
src/base-container/tests/BaseContainer.test.jsx

Remove rebrand experiment code from Authn
[VAN-1858](https://2u-internal.atlassian.net/browse/VAN-1858)

fix: remove rebrand experiment from authn

---

src/register/RegistrationPage.jsx
src/register/data/optimizelyExperiment/track.js

Adding event on submit btn click on invalid form data. Simplified registration experiment
[VAN-1827](https://2u-internal.atlassian.net/browse/VAN-1827)
Locally
|Before|After|

feat: add invalid form submit click event

---

src/register/RegistrationPage.jsx

Event was being fired for 2nd step too for simplified registration variation

fix: invalid form submit btn event error

---

src/register/RegistrationFields/EmailField/EmailField.jsx
src/register/RegistrationFields/UsernameField/UsernameField.jsx
src/register/RegistrationPage.jsx
src/register/data/selectors.js
src/register/data/utils.js

In this PR we are optimizing the `registration` component by using reducer state more granular which helps to minimize the component rendering on dependent state change along with following best practices.
Docs: Selectors should be as granular as possible
Reference: https://react-redux.js.org/api/hooks
[VAN-1890](https://2u-internal.atlassian.net/browse/VAN-1890)
Locally

use useSelector with granular approach in registration component to minimize rendering

---

src/base-container/tests/BaseContainer.test.jsx
src/common-components/tests/EmbeddedRegistrationRoute.test.jsx
src/login/tests/LoginFailure.test.jsx
src/progressive-profiling/tests/ProgressiveProfiling.test.jsx
src/recommendations/ProductCard/BaseCard/index.jsx
src/recommendations/ProductCard/index.jsx
src/recommendations/data/tests/mockedData.js
src/recommendations/data/tests/parser.test.jsx
src/reset-password/tests/ResetPasswordPage.test.jsx

Resolved console warnings for different tests. See the table below for details.
[VAN-1888](https://2u-internal.atlassian.net/browse/VAN-1888)
By updating tests
|Error|Fix|
|<img width="1247" alt="Screenshot 2024-04-01 at 12 51 30 PM" src="https://github.com/openedx/frontend-app-authn/assets/40633976/c61c9632-eb57-4a17-8049-7d814672ac7d">|No child component was passed to the base container. Added a simple div to the fix this.
|<img width="1247" alt="Screenshot 2024-04-01 at 12 51 09 PM" src="https://github.com/openedx/frontend-app-authn/assets/40633976/0a771673-a8a8-466e-8c8a-d385102f2766"><img width="1247" alt="Screenshot 2024-04-01 at 12 50 54 PM" src="https://github.com/openedx/frontend-app-authn/assets/40633976/eabdadd7-0351-429f-8e7c-073a746583d9"><img width="1247" …

fix: resolve console warnings in tests

---

.github/workflows/ci.yml

Moving back to codecov v3. Details: https://github.com/openedx/wg-frontend/issues/177#issuecomment-2032690280

fix: codecov not running on PRs

---

src/common-components/ThirdPartyAuth.jsx

Cosmetic improvements for the login/registration page. Changes in React are related to the situation when third-party login providers is disabled, but when switching between Login and Registration tabs, we still see a preloader that is not necessary in this situation.
https://user-images.githubusercontent.com/19806032/222164313-f1e985d9-47e1-4b18-8b27-8280f5c6a7fd.mov
And sass changes are related to the suggested username field, which is too short and can be extended to match the neighboring inputs.
After making our changes, we no longer see preloaders in cases where third-party login providers are turned off.
https://user-images.githubusercontent.com/19806032/222174870-e76fe894-1a63-448b-bc08-ffd9df8dca0b.mov
And suggested username field looks pretty

feat: Auth form visual enhancements (master)

---

src/register/RegistrationPage.jsx
src/register/data/optimizelyExperiment/helper.js
src/sass/_registration.scss

Putting minimum width for btn to avoid de creasing width on loader.

fix: fix register button width

---

src/register/data/optimizelyExperiment/helper.js

Loader was not appearing on first step of control variant
Locally
|Before|After|

fix: fix register button loader for control

---

src/forgot-password/ForgotPasswordPage.jsx
src/reset-password/ResetPasswordPage.jsx
src/reset-password/tests/ResetPasswordPage.test.jsx

Add page event for reset password page 
[VAN-1929](https://2u-internal.atlassian.net/browse/VAN-1929)
Has been tested locally

feat:  add page event for reset password

---

src/register/data/tests/utils.test.js
src/register/data/utils.js

If there is already an existing email error in the field, the IsFormValid method will return a false value, and the submit call will not be executed.
[VAN-1910](https://2u-internal.atlassian.net/browse/VAN-1910)
Unit Test
|Before|After|

fix: frontend validation on email field

---

src/common-components/SocialAuthProviders.jsx
src/common-components/tests/SocialAuthProviders.test.jsx
src/register/components/ConfigurableRegistrationForm.jsx

Setting marketing opt in in cookie for sso flow.
|Before|After|

fix: set marketing opt in in cookie for sso

---

src/common-components/RedirectLogistration.jsx
src/common-components/tests/SocialAuthProviders.test.jsx
src/data/utils/cookies.js
src/data/utils/index.js
src/register/RegistrationPage.jsx

-remove marketingEmailsOptIn cookie on successful registration
- fix tests
Test through unit tests and manual testing

fix: remove cookie

---

src/common-components/ThirdPartyAuthAlert.jsx
src/login/LoginPage.jsx
src/register/RegistrationPage.jsx

Fix marketingEmailsOptIn null value issue for SSO flow on onboarding component
[VAN-2013](https://2u-internal.atlassian.net/browse/VAN-2013)
Test through unit tests and manual testing

fix: fix marketingEmailsOptIn null value

---

src/recommendations/track.js
src/register/RegistrationFields/NameField/validator.js

Fix the following datadog JS errors
- TypeError: (null is not an object (evaluating 'e.trim')
- TypeError: (Cannot read properties of undefined (reading 'name')
- TypeError: (Cannot read properties of null (reading 'trim')
- TypeError: (e.productSource is undefined)
- TypeError: (Cannot read property 'name' of undefined)
- TypeError: (undefined is not an object (evaluating 'e.productSource.name')
[VAN-2035](https://2u-internal.atlassian.net/browse/VAN-2035)
|Before|After|

fix: fix datadog js errors

---

src/register/RegistrationPage.test.jsx
src/register/components/tests/ConfigurableRegistrationForm.test.jsx
src/register/data/utils.js

- Convert totalRegistrationTime to snake case
[VAN-1816](https://2u-internal.atlassian.net/browse/VAN-1816)
- Tested locally
Here is the backend PR https://github.com/openedx/edx-platform/pull/35333

fix: covert totalRegistrationTime to snake case

---

src/common-components/UnAuthOnlyRoute.jsx

fix authenticated user redirects to 404 if the token is invalid for password reset
[VAN-2052](https://2u-internal.atlassian.net/browse/ VAN-2052)
tested through local testing

fix: password reset redirection

---

.github/CODEOWNERS
.github/pull_request_template.md
CODEOWNERS
README.rst
catalog-info.yaml
openedx.yaml

[INF-1551](https://2u-internal.atlassian.net/browse/INF-1551)
Description
As part of the maintainer ship program, we updated the catalog file of the Authn MFE to confirm that Edx-Infinity team will be maintaining the repo.
The file needs to be updated according to [OEP-55: Project Maintainers — Open edX Proposals 1.0 documentation](https://open-edx-proposals.readthedocs.io/en/latest/processes/oep-0055-proc-project-maintainers.html#documenting-maintainers)

docs: updated catalog-info file for authn MFE

---

.eslintrc.js
example.env.config.js
webpack.dev.config.js

- Updated webpack.prod.config.js file to resolve the src in node_module

build: updated webpack.prod.config.js

---

src/register/components/ConfigurableRegistrationForm.jsx

[INF-1661](https://2u-internal.atlassian.net/browse/INF-1661)
Description
Fix for opt-out event text and name

fix: fixed opt out event text

---

src/register/RegistrationPage.jsx

[INF-1661](https://2u-internal.atlassian.net/browse/INF-1661)
- Removed duplicate events on the registration page

fix: removed duplicate registration events

---

src/login/ChangePasswordPrompt.jsx
src/login/tests/ChangePasswordPrompt.test.jsx
src/login/tests/LoginFailure.test.jsx

[INF-1661](https://2u-internal.atlassian.net/browse/INF-1661)
Fire event on nudge password change modal close

fix: fixed nudge password edge case

---

src/cohesion/index.js

[INF-1666](https://2u-internal.atlassian.net/browse/INF-1666)
**Description**
Update cohesion script requested by redventures
[edx-cohesion-snippet.html](https://drive.google.com/file/d/1iLnruGe_DvAH7XW_N4viQxbAyovm1ruk/view?usp=drive_link)

feat: added update cohesion script

---

src/data/utils/dataUtils.js
src/login/ChangePasswordPrompt.jsx
src/login/tests/ChangePasswordPrompt.test.jsx
src/login/tests/LoginPage.test.jsx
src/progressive-profiling/tests/ProgressiveProfiling.test.jsx
src/register/RegistrationPage.test.jsx
src/register/components/tests/ThirdPartyAuth.test.jsx

[INF-1668](https://2u-internal.atlassian.net/browse/INF-1668)
Description
Fix for event (NS_BINDING_ABORTED) abort in firefox  in nudge password change due to redirection after login/registration

fix: delaying  nudge password redirection

---

package.json

This reverts commit 8a27b8cc37ceea5164d3f494f9bca21cf1029b88.

Revert "fix(deps): update dependency @testing-library/react to v16"

---

package-lock.json

Reverts openedx/frontend-app-authn#1313

Revert "fix(deps): update dependency algoliasearch-helper to v3.22.5"

---

.github/workflows/ci.yml
package-lock.json
package.json

chore: rebase 2u-main

---

src/login/AccountActivationMessage.jsx
src/login/messages.jsx
src/login/tests/AccountActivationMessage.test.jsx

[INF-1704](https://2u-internal.atlassian.net/browse/INF-1704)
ACTIVATION_EMAIL_SUPPORT_LINK  is unavailable which needed to be replaced with info@edx.com

fix: fixed account activation error message

---

src/register/RegistrationFields/UsernameField/UsernameField.jsx
src/register/data/sagas.js
src/sass/_registration.scss

Username suggestions functionality has been corrected to ensure proper behaviour.
- fixed issue with suggestions being displayed in the wrong place;
- added the ability to navigate through suggestions using the keyboard.
**Related Pull Requests**
PR to the open-release/redwood.master branch: https://github.com/openedx/frontend-app-authn/pull/1279
PR to the master branch: https://github.com/openedx/frontend-app-authn/pull/1270
**1. suggestions being displayed in the wrong place**
Open register page -> Enter some string into field "Full name" (e.g. Jack Smith) -> Click on field "Public username"
https://github.com/openedx/frontend-app-authn/assets/40792129/40d292b5-3187-43bc-8325-cadce65b10ce
**2. impossible to enter suggestions field using the keyboard**
Open register page -> Enter some …

fix: the display of username suggestions

---

src/MainApp.jsx

Updated the RV cohesion script. The updated Script handles consent-related configurations.

feat: updated cohesion script

---

src/MainApp.jsx

[INF-1798](https://2u-internal.atlassian.net/jira/software/c/projects/INF/boards/1994?selectedIssue=INF-1798)
Red Ventures has provided us with a script that includes all of the initializing needed to get Cohesion running in the Authn page. This ticket is to replace the boilerplate code in Authn MFE.

feat: updated cohesion snippet

---

src/MainApp.jsx
src/cohesion/cohesion.scss
src/index.jsx

Description
[INF-1798](https://2u-internal.atlassian.net/jira/software/c/projects/INF/boards/1994?selectedIssue=INF-1798)
Red Ventures has provided us with a script that includes all of the initializing needed to get Cohesion running in the Authn page. This ticket is to replace the style tag in Authn MFE.

fix: removed style tag for updated cohesion script

---

src/MainApp.jsx
src/cohesion/cohesion.scss
src/index.jsx

Reverts openedx/frontend-app-authn#1434

Revert "fix: removed style tag for updated cohesion script"

---

src/MainApp.jsx

Reverts openedx/frontend-app-authn#1433

Revert "feat: updated cohesion snippet"

---

public/index.html
src/MainApp.jsx

Description
[INF-1798](https://2u-internal.atlassian.net/jira/software/c/projects/INF/boards/1994?selectedIssue=INF-1798)
Moving updated cohesion snippet to index.html file which could help avoiding two instances of cohesion script loading.

refactor: moved updated script to index.html

---

package-lock.json
package.json
public/index.html
public/robots.txt
webpack.dev.config.js
webpack.prod.config.js

[INF-1819](https://2u-internal.atlassian.net/browse/INF-1819)
blocked web crawlers for auth MFE

fix: blocked web crawlers for auth MFE

---

src/cohesion/trackers.js

Created a fix for window.tagular is not a function

fix: fixed tagular console error if cohesion script is not loaded

---

package-lock.json
package.json

Upgraded Paragon version for authn.

feat: upgraded package for paragon

---

package-lock.json
package.json

Resolves https://github.com/openedx/frontend-app-authn/issues/1467

fix: properly set background color for floating labels

---

package-lock.json

Sync master to design tokens

---

src/register/components/RegistrationFailure.jsx
src/register/data/constants.js
src/register/messages.jsx

This PR adds an exception case to handle prevent user registrations with usernames containing forbidden terms.
https://2u-internal.atlassian.net/browse/INF-2109
|Before|After|

chore: Handle forbidden username exceptions on registration
