openedx/frontend-app-authn

- .tx/config
- package-lock.json
- package.json
> Add Transifex config.

- src/data/reducers.js
- src/data/sagas.js
- src/index.jsx
- src/reset-password/InvalidToken.jsx
- src/reset-password/ResetFailure.jsx
- src/reset-password/ResetPasswordPage.jsx
- src/reset-password/ResetSuccess.jsx
- src/reset-password/Spinner.jsx
- src/reset-password/data/actions.js
- src/reset-password/data/reducers.js
- src/reset-password/data/sagas.js
- src/reset-password/data/selectors.js
- src/reset-password/data/service.js
- src/reset-password/index.js
- src/reset-password/messages.js
- src/reset-password/tests/ResetPasswordPage.test.jsx
- src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap
Adds pages for;
- Password reset form.
- Successful reset message
- Invalid token message.
Adds sagas/service code for;
- Token validation
- Password reset
VAN-77
> Adds Reset password functionality.

- src/reset-password/ResetPasswordPage.jsx
- src/reset-password/data/actions.js
- src/reset-password/data/sagas.js
- src/reset-password/data/service.js
- src/reset-password/data/tests/sagas.test.js
- src/reset-password/tests/ResetPasswordPage.test.jsx
- src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap
We need to enhance forgot password feature to enable user to get reset password link on his/her secondary email address if set inside db. User should be able to get reset link on secondary email address and use it to recover account incase he/she is somehow blocked from using primary email address.
VAN-18
> Enable forgot password functinality for secondary email.

- src/logistration/LoginFailure.jsx
- src/logistration/LoginPage.jsx
- src/logistration/data/actions.js
- src/logistration/data/reducers.js
- src/logistration/data/sagas.js
- src/logistration/tests/LoginPage.test.jsx
- src/logistration/tests/__snapshots__/LoginPage.test.jsx.snap
This patch handles 400 error for login
page and displays backend error to learner.
VAN-105
> Adds error handling to Login page.

- src/reset-password/ResetSuccess.jsx
- src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap
ACs:
1. the message copy for MFE needs to be updated to match the hyperlink text same as old FE.
2. Message placeholder should be green for success.
VAN-106
> modify reset password message and background color

- src/logistration/LoginFailure.jsx
- src/logistration/LoginPage.jsx
- src/logistration/_style.scss
- src/logistration/data/constants.js
- src/logistration/data/sagas.js
- src/logistration/data/selectors.js
- src/logistration/messages.jsx
- src/logistration/tests/LoginFailure.test.jsx
- src/logistration/tests/LoginPage.test.jsx
- src/logistration/tests/__snapshots__/LoginFailure.test.jsx.snap
- Added a `switch case` statement in `LoginFailureMessage` component to select messages based on `errorCode`. Currently the default case is using error messages sent from platform but it will be removed once we add errorCode to backend for all exceptions.
- Updated the font color for the "Sign In" heading on login page.
- Added tests for `LoginFailureMessage`
**Note**: Currently I am sending both the errorCode and value (errors from backend) to `LoginFailureMessage` but once all errorCodes are added to backend, only errorCode should be sent.
Ticket : [VAN-128](https://openedx.atlassian.net/browse/VAN-128)
> Add password compliance workflow

- src/logistration/LoginFailure.jsx
- src/logistration/data/constants.js
- src/logistration/data/sagas.js
- src/logistration/data/tests/sagas.test.js
- src/logistration/tests/LoginFailure.test.jsx
- src/logistration/tests/__snapshots__/LoginFailure.test.jsx.snap
This handles the cases where some internal server error occurs and no error message is shown to users.
[VAN-95](https://openedx.atlassian.net/browse/VAN-95)
> Add error handling for 500 status code

- src/logistration/RegistrationPage.jsx
- src/logistration/data/service.js
- src/logistration/tests/RegistrationPage.test.jsx
When registering via SSO, populate registration fields with user data acquired from the social auth pipeline.
[VAN-238](https://openedx.atlassian.net/browse/VAN-238)
> populate registration fields

- src/logistration/_style.scss
Updated Facebook SSO button color according to their brand guidelines also fixed logo size.
VAN-296
> Update Facebook SSO button.

- src/logistration/_style.scss
UX has requested blue underlined links and I have update the <Alert.Link> class .alert-link to reflect this change
Before:
After:
> VAN-304: update alert link class

- src/_style.scss
- src/common-components/InstitutionLogistration.jsx
- src/common-components/SocialAuthProviders.jsx
- src/common-components/tests/__snapshots__/SocialAuthProviders.test.jsx.snap
- src/login/LoginHelpLinks.jsx
- src/login/LoginPage.jsx
- src/login/tests/LoginPage.test.jsx
- src/login/tests/__snapshots__/LoginPage.test.jsx.snap
- src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
VAN-321
Incorporated UX review feedback for the login page. Following are the changes made in this PR:
Before | After
------------ | -------------
> Incorporate UX review for login page.

- src/register/RegistrationFailure.jsx
- src/register/data/sagas.js
- src/register/data/tests/sagas.test.js
- src/register/messages.jsx
- src/register/tests/RegistrationPage.test.jsx
- src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
There is a need to handle 500 server errors on MFE so that they can be properly communicated with end-users.
Now, it looks like the following:
VAN-281
> Handle 500 api response

- src/common-components/APIFailureMessage.jsx
- src/common-components/messages.jsx
- src/forgot-password/ForgotPasswordPage.jsx
- src/forgot-password/data/actions.js
- src/forgot-password/data/reducers.js
- src/forgot-password/data/sagas.js
- src/forgot-password/messages.js
- src/forgot-password/tests/ForgotPasswordPage.test.jsx
There is a need to handle 500 server errors on MFE so that they can be properly communicated with end-users.
Now, it looks like the following:
VAN-281
> handle 500 on forgot password page

- src/reset-password/ResetPasswordPage.jsx
- src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap
It's appearing due to `tabindex` set on the container.
> Remove blue border appearing in safari.

- src/forgot-password/ForgotPasswordPage.jsx
- src/forgot-password/messages.js
- src/forgot-password/tests/ForgotPasswordPage.test.jsx
- src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
van-316
Email validation removed `onChange` event.
Paragon helper text added.
Updated the error message incase of invalid email
> password page email validation removed

- src/forgot-password/ForgotPasswordPage.jsx
- src/forgot-password/tests/ForgotPasswordPage.test.jsx
Changes:
- Show error message banner on top of form only on form submission
- If an alert banner is present, update error message only on re-form submission and not on blur event
> update and show error alert on form submission only

- src/common-components/AuthnValidationFormGroup.jsx
- src/common-components/index.jsx
- src/forgot-password/ForgotPasswordPage.jsx
- src/forgot-password/tests/ForgotPasswordPage.test.jsx
- src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
- src/login/LoginPage.jsx
- src/login/tests/LoginPage.test.jsx
- src/login/tests/__snapshots__/LoginPage.test.jsx.snap
- src/register/RegistrationPage.jsx
- src/register/messages.jsx
- src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
- src/reset-password/ResetPasswordPage.jsx
- src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap
We are moving away from paragon ValidationFormGroup to a custom component that would enable following changes
1) Enable widgets to show label as placeholder as initial value.
2) Enable widgets to show help text and label on top on focus in.
3) Enable widgets to show label as placeholder on focus out.
**Initial Rendering:**
**Focus in:**
**Focus out:**
> Form fields ux feedback

- src/reset-password/ResetPasswordPage.jsx
- src/reset-password/tests/ResetPasswordPage.test.jsx
Currently if there is an error above the form field from previous tries, it is displayed under the field on correct password submission.
> fix bug: Error on correct password submission

- src/login/LoginPage.jsx
- src/reset-password/tests/ResetPasswordPage.test.jsx
Fixed:
- If an error occurs on sign in page after password reset request,
the confirmation message is not dismissed.
[VAN-347](https://openedx.atlassian.net/browse/VAN-347)
> Hide Confirmation Alert on Form Submission

- src/forgot-password/ForgotPasswordPage.jsx
- src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
- src/login/LoginPage.jsx
- src/login/tests/__snapshots__/LoginPage.test.jsx.snap
- src/register/RegistrationPage.jsx
- src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
- src/reset-password/ResetPasswordPage.jsx
- src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap
The `onBlur` event's priority is higher than `onClick` and rerenders the component before the click event fires.
VAN-352
Sandbox: https://authn-van.sandbox.edx.org/login
> Fix buttons needs to click twice issue.

- src/common-components/RedirectLogistration.jsx
- src/login/tests/LoginPage.test.jsx
If redirect url has auth complete url in it, it means that the redirect url is for multiple enterprise selection page and user must be redirected to that page first.
example url = http://localhost:18000/enterprise/select/active/?success_url=/auth/complete/google-oauth2/
This check mimics the [following scenario](https://github.com/edx/edx-platform/blob/50bb70298cd30170e5572dfd9e7d2914dec3a4cd/lms/static/js/student_account/views/AccessView.js#L319-L320) from FE:
```javascript
loginComplete: function() {
if (this.thirdPartyAuth && this.thirdPartyAuth.finishAuthUrl) {
multipleEnterpriseInterface.check(this.thirdPartyAuth.finishAuthUrl);
// Note: the third party auth URL likely contains another redirect URL embedded inside
} else {
multipleEnterpriseInterface.check(this.nextUrl);
}
},
``` …
> Add multiple enterprise redirect

- src/forgot-password/ForgotPasswordPage.jsx
- src/register/RegistrationPage.jsx
- src/reset-password/ResetPasswordPage.jsx
`AuthnCustomValidationFormGroup` uses label as placeholder for input element instead of `placeholder` (It is also not part of the default props of the component).
https://github.com/edx/frontend-app-authn/blob/845b8c85fc8579a6be2318440658a935905b7ac3/src/common-components/AuthnValidationFormGroup.jsx#L63
> Remove unused placeholder prop

- src/common-components/APIFailureMessage.jsx
- src/common-components/index.jsx
- src/reset-password/ResetPasswordPage.jsx
- src/reset-password/data/actions.js
- src/reset-password/data/reducers.js
- src/reset-password/data/sagas.js
- src/reset-password/data/tests/sagas.test.js
- src/reset-password/messages.js
- src/reset-password/tests/ResetPasswordPage.test.jsx
- src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap
The changes in this PR will make the MFE capable to handle the api failures while validating the password reset token in addition to the password reset form submission.
Here are the screenshots:
[VAN-281](https://openedx.atlassian.net/browse/VAN-281)
> handle api failures gracefully

- src/register/RegistrationPage.jsx
- src/register/tests/RegistrationPage.test.jsx
if `REGISTRATION_OPTIONAL_FIELDS` is empty, do not render optional field button
> fix optional field not available

- src/_style.scss
- src/common-components/EnterpriseSSO.jsx
- src/data/utils/dataUtils.js
- src/data/utils/index.js
- src/login/LoginPage.jsx
- src/register/RegistrationPage.jsx
Now the url could also be of the form
?next=/dashboard?tpa_hint=oa2-google-oauth2
to be backward compatible with old url.
VAN-42
> Fix to let  tpa_hint url have ? instead of &

- src/common-components/messages.jsx
- src/common-components/tests/ConfirmationAlert.test.jsx
- src/forgot-password/messages.js
- src/forgot-password/tests/ForgotPasswordPage.test.jsx
- src/login/messages.jsx
- src/login/tests/LoginFailure.test.jsx
- src/login/tests/LoginPage.test.jsx
- src/login/tests/__snapshots__/LoginPage.test.jsx.snap
- src/register/messages.jsx
- src/register/tests/RegistrationPage.test.jsx
- src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
- src/reset-password/messages.js
- src/reset-password/tests/ResetPasswordPage.test.jsx
- src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap
Register page:
Login page:
Password Assistance
Reset Password page:
[VAN-393](https://openedx.atlassian.net/browse/VAN-393)
> VAN-393: use sentence case for text

- src/_style.scss
- src/common-components/SocialAuthProviders.jsx
- src/common-components/tests/SocialAuthProviders.test.jsx
- src/common-components/tests/__snapshots__/SocialAuthProviders.test.jsx.snap
- src/login/tests/__snapshots__/LoginPage.test.jsx.snap
- src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
Keep the social auth buttons left aligned and two in each row.
Ticket: https://openedx.atlassian.net/browse/VAN-397
-----
|Login|Register|
|------|-------|
|<img width="558" alt="Screenshot 2021-02-23 at 4 20 05 PM" src="https://user-images.githubusercontent.com/40633976/108837019-6b24ab00-75f3-11eb-96e9-f597225995bf.png"> | <img width="558" alt="Screenshot 2021-02-23 at 4 20 16 PM" src="https://user-images.githubusercontent.com/40633976/108837036-6f50c880-75f3-11eb-9ecc-2b1a482bacb0.png">|
> VAN-397: Realign social auth providers

- src/common-components/APIFailureMessage.jsx
- src/common-components/messages.jsx
- src/data/constants.js
- src/forgot-password/ForgotPasswordPage.jsx
- src/reset-password/ResetPasswordPage.jsx
- src/reset-password/data/sagas.js
- src/reset-password/data/tests/sagas.test.js
- src/reset-password/messages.js
- src/reset-password/tests/ResetPasswordPage.test.jsx
* This patch implements ratelimit handling code for
validate token and password reset end points.
* Adds graceful error messages for such case
* 
**Validate token:**
**Reset Password:**
VAN-312
> Ratelimit handling for validate and password reset endpoints.

- src/_style.scss
Fixed two issues in this PR:
- Made SSO buttons responsive. The reason for justifying content to centre for screen size <= 600 is because if I keep it left align there is a minor unwanted gap on the right side only. Keeping it centre aligned divides that gap and is not noticeable. 
- The previous fix for removing unwanted space from `Privacy Policy` hyperlink was not working on stage. I have added the sr-only class to the  `<span />` inside hyperlink. The span is for screen readers only and hence `.sr-only` class seems fitting to add here.
----
**The highlighted blue area represents the form size:**
> Fix responsiveness issue of sso buttons

- src/_style.scss
Due to a recent change, password reset alert banner stopped showing the hyperlink to sign back. It was due to the generic css that was added in the styles. I have restricted it to honor code only
> Fix: All span inside anchor tag have sr-only class

- src/i18n/index.jsx
Prospectus set `es` code for Spanish instead of es-419. Added `es` option and pointed to `es-419` strings so that we don't need to maintain two separate instances of strings for the same language in Transifex.
> Add es language option.

- src/common-components/ConfirmationAlert.jsx
- src/login/LoginFailure.jsx
- src/login/tests/__snapshots__/LoginPage.test.jsx.snap
- src/register/OptionalFields.jsx
- src/register/RegistrationFailure.jsx
- src/register/RegistrationPage.jsx
- src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
Suppressed PII from logistration pages to enable Hotjar. Data entered in forms is by default suppressed by Hotjar. PII Suppression is done by adding `data-hj-suppress` as an attribute or class. From Hotjar's documentation:
```html
<p class="data-hj-suppress">Suppress me.</p>
<p>Do not suppress me.</p>
```
----
----
Ticket: [VAN-290](https://openedx.atlassian.net/browse/VAN-290)
> Enable Hotjar for Authn MFE

- src/_style.scss
Purpose of adding the fix width is to sync SSO buttons and
inputs fields widths for the screen 600 and above.
VAN-353
before the fix:
https://user-images.githubusercontent.com/8156837/110381052-cbe3c700-807a-11eb-9314-86188f695ce4.mov
after the fix:
https://user-images.githubusercontent.com/8156837/110381103-d900b600-807a-11eb-9875-c797afa7fd8f.mov
> Added width for inputs fields in form-control class.

- src/register/RegistrationPage.jsx
- src/register/tests/RegistrationPage.test.jsx
On FE if third party auth session has expired and user tried to register, an error message is shown. This is however not happening on MFE because we are not sending `social_auth_provider` param in the registration request which breaks the logic at the backend and incorrect message is shown to the user.
If current provider is present, then send the `social_auth_provider` in the registration payload. If there is no running pipeline at the backend at the time of submission, correct error message is shown on MFE:
|Before|After|
|----|-----|
|<img width="552" alt="Screenshot 2021-03-09 at 5 33 50 PM" src="https://user-images.githubusercontent.com/40633976/110471180-a2b84a80-80fd-11eb-84e2-fa040f0d55bc.png">|<img width="552" alt="Screenshot 2021-03-09 at 5 02 57 PM" …
> Send social_auth_provider param upon registration

- src/_style.scss
- src/register/RegistrationPage.jsx
- src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
> Inline links added for tos on register page

- src/common-components/AuthnValidationFormGroup.jsx
- src/forgot-password/ForgotPasswordPage.jsx
- src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
- src/login/LoginPage.jsx
- src/login/tests/__snapshots__/LoginPage.test.jsx.snap
- src/register/RegistrationPage.jsx
- src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
- src/reset-password/ResetPasswordPage.jsx
- src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap
This would enable screen readers to readout
field errors to users.
VAN-387
> Add aria-invalid to fields.

- src/_style.scss
- src/common-components/SocialAuthProviders.jsx
- src/common-components/messages.jsx
- src/common-components/tests/__snapshots__/SocialAuthProviders.test.jsx.snap
- src/login/tests/LoginPage.test.jsx
- src/login/tests/__snapshots__/LoginPage.test.jsx.snap
- src/register/tests/RegistrationPage.test.jsx
- src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
- Add `sr-only` span for all SSO buttons (`sr-only` means invisible/readable by screen reader users only)
- Moved the provider name outside the div and inside the button. 
- Updated tests to reflect the changes
Ticket: https://openedx.atlassian.net/browse/VAN-384
> VAN-384: Add accessible names for TPA buttons

- src/login/LoginPage.jsx
- src/login/tests/__snapshots__/LoginPage.test.jsx.snap
We use headings (`<h1>`, `<h2>`, etc.) to give a page semantic structure. These are particularly useful for blind learners.  General accessibility guidelines for use of headers include:
- there should be an H1
- there should be only one H1
- Heading levels should correspond to semantic structure consistently (no inversions, changing levels that look like peers, etc.)
----
- Converted H3 to H1
- Added the css of H3 to H1 so that the page looks same as it did before
> VAN-380: Add H1 heading to Login Page

- src/register/RegistrationFailure.jsx
- src/register/data/constants.js
- src/register/data/sagas.js
- src/register/data/tests/sagas.test.js
- src/register/messages.jsx
- src/register/tests/RegistrationPage.test.jsx
As part of adding ratelimit to registration, we need to make sure MFE works and shows error messages as expected.
Note: Currently I am ignoring the openedX `403` error regarding [required third party auth](https://github.com/edx/edx-platform/blob/3cdbb5b36aaf81b0459823db9a2c9ca40f9d7b7a/openedx/core/djangoapps/user_authn/views/register.py#L513-L517) and displaying a generic message _"too many failed attempts"_. Once we add support for openedX we need to make sure the appropriate error message is show for different `403` errors.
Tickert: [VAN-302](https://openedx.atlassian.net/browse/VAN-302)
> Handle ratelimit error for registration endpoint

- package-lock.json
- package.json
- src/common-components/AuthnValidationFormGroup.jsx
- src/common-components/tests/AuthnValidationFormGroup.test.jsx
- src/forgot-password/ForgotPasswordPage.jsx
- src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
- src/login/LoginPage.jsx
- src/login/tests/__snapshots__/LoginPage.test.jsx.snap
- src/register/OptionalFields.jsx
- src/register/RegistrationPage.jsx
- src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
- src/reset-password/ResetPasswordPage.jsx
- src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap
This patch does the following things;
1) Removes overrides
2) Upgrade Paragon to 13.17.3, which handles 3:1 contrast for text fields by default.
VAN-381
> Add 3:1 contrast to all form text field.

- src/common-components/InstitutionLogistration.jsx
- src/forgot-password/ForgotPasswordPage.jsx
- src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
- src/register/RegistrationPage.jsx
- src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
- src/reset-password/ResetPasswordPage.jsx
- src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap
We use headings (`<h1>`, `<h2>`, etc.) to give a page semantic structure. These are particularly useful for blind learners. General accessibility guidelines for use of headers include:
- there should be an H1
- there should be only one H1
- heading levels should correspond to semantic structure consistently (no inversions, changing levels that look like peers, etc.)
----
####Notes:
- Converted H3 to H1
- Added the css of H3 to H1 so that the page looks same as it did before
- This change was already done for login page here: https://github.com/edx/frontend-app-authn/pull/216
Ticket: https://openedx.atlassian.net/browse/VAN-426
> Update h3 headings to h1 for page semantics

- src/register/RegistrationPage.jsx
- src/register/tests/RegistrationPage.test.jsx
Once the user has signed up successfully, send custom user attribute to hotjar. These can be used to configure hotjar surveys and other feedback tools. 
- I am following this guide to setup user attributes: https://help.hotjar.com/hc/en-us/articles/360038394053/
- I am not sending edX user id to identify call and it will automatically use the hotjar user id. 
- **Test Account** attribute will be removed after testing 
[VAN-291](https://openedx.atlassian.net/browse/VAN-291)
> Send user attributes to hotjar

- .env.development
- src/register/OptionalFields.jsx
- src/register/RegistrationPage.jsx
- src/register/tests/RegistrationPage.test.jsx
As part of VAN-405, changes are required to remove the optional fields, instead of removing them completely from code base I have made them configurable which will allow us to enable it back if we need it. If it's not needed in future we can remove it completely.
I have removed custom class from the fields because enabling some fields was causing css to break
[VAN-405](https://openedx.atlassian.net/browse/VAN-405)
> Make optional fields configurable

- src/data/utils/dataUtils.js
- src/data/utils/index.js
- src/forgot-password/ForgotPasswordPage.jsx
- src/login/LoginPage.jsx
- src/register/RegistrationFailure.jsx
- src/reset-password/ResetPasswordPage.jsx
Check if `scrollBehavior` is supported otherwise fallback to two arguments `window.scrollTo(x-coord, y-coord)`.
VAN-439
**Sandbox:** https://authn-van.sandbox.edx.org/login
1. Open a reset password link for an account on the above sandbox in chrome 42 or lower and try to reset your password.
2. Notice that user can successfully reset their password and scroll is also working.
> Fix scroll error for older browsers.

- src/_style.scss
- src/common-components/SocialAuthProviders.jsx
- src/common-components/tests/__snapshots__/SocialAuthProviders.test.jsx.snap
- src/login/tests/__snapshots__/LoginPage.test.jsx.snap
- src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
updated social auth providers to match for login and register page
|Before|After|
|---|---|
|Before|After|
|---|---|
> VAN-405: Redesign social auth provider component

- package-lock.json
- package.json
- src/common-components/tests/AuthnValidationFormGroup.test.jsx
- src/forgot-password/tests/__snapshots__/ForgotPasswordPage.test.jsx.snap
- src/login/tests/__snapshots__/LoginPage.test.jsx.snap
- src/register/OptionalFields.jsx
- src/register/tests/__snapshots__/RegistrationPage.test.jsx.snap
- src/reset-password/tests/__snapshots__/ResetPasswordPage.test.jsx.snap
Added back compatibility for optional fields by updating them to new paragon components, these can be used if we decide to enable optional fields in future.
- updated paragon package
- updated optional fields to use new paragon components
- some tests needed fixing after updating to new paragon component
> Update optional fields to use updated paragon components

- src/_style.scss
- src/common-components/LargeScreenRightLayout.jsx
- src/common-components/Logistration.jsx
- src/common-components/MediumScreenLayout.jsx
The margin added to `LargeScreenRightLayout` was making the page "scrollable". This commit fixes that issue and also updated the padding for mobile view to match the designs.
> Fix form padding and margins

- src/common-components/FormGroup.jsx
- src/common-components/ThirdPartyAuthAlert.jsx
- src/common-components/messages.jsx
- src/common-components/tests/Logistration.test.jsx
- src/common-components/tests/ThirdPartyAuthAlert.test.jsx
- src/common-components/tests/__snapshots__/ThirdPartyAuthAlert.test.jsx.snap
- src/login/tests/LoginPage.test.jsx
- src/register/RegistrationFailure.jsx
- src/register/RegistrationPage.jsx
- src/register/UsernameField.jsx
- src/register/data/actions.js
- src/register/data/constants.js
- src/register/data/reducers.js
- src/register/data/sagas.js
- src/register/data/selectors.js
- src/register/data/service.js
- src/register/data/tests/sagas.test.js
- src/register/messages.jsx
- src/register/tests/RegistrationPage.test.jsx
- handle empty form submission
- handle validation error messages and registration error messages
- updated third party auth alert to use platform name from config
- updated validationDecision selector to consider registration errors (Only one can be present at a time, if validations rate limit only then the registration request is possible, hence it can be maintained using a single prop)
- registration failure component now displays generic message for all the error codes returned by backend except if error code matches one of the error messages in `RegistrationFailure`
|Generic registration error|Social Auth Message|
|-----|----|
Test PR with https://github.com/edx/edx-platform/pull/27476
[VAN-288](https://openedx.atlassian.net/browse/VAN-288)
> handle register page form submission

- src/register/RegistrationPage.jsx
Clear the error state on the warning otherwise it won't allow user to submit the form.
> fix: clear error state on warning

- public/index.html
- src/register/RegistrationPage.jsx
- src/register/tests/RegistrationPage.test.jsx
Conduct an A/B test via Optimizely where 50% of users will see optional fields and the other 50% of users will not see these fields on the registration form.
Run this test for a week; we are looking for an answer to the question:
What impact does removing optional fields from the registration form has on the registration rate?
- Measure OGSP registration rate.
- Measure registration page conversion rate.
The 50% of traffic that will not be shown optional fields will set the `optimizelyExperimentName` to `hide_optional_fields` in optimzely
Ticket: https://openedx.atlassian.net/browse/VAN-487
> VAN-487: Add optimizely experiment

- src/common-components/RedirectLogistration.jsx
- src/register/RegistrationPage.jsx
- src/register/tests/RegistrationPage.test.jsx
- src/welcome/WelcomePage.jsx
- If optimizely experiment name is set to `progressive_profiling_phase1` redirect user to welcome page once he has successfully registered. Don't show user optional fields in this variation.
- For control group (`optimizelyExperimentName !== 'progressive_profiling_phase1'`) fire optimizely even on successful registration.
- For variation group (`optimizelyExperimentName === 'progressive_profiling_phase1'`) fire event on skip/submit on progressive profiling page.
Ticket: https://openedx.atlassian.net/browse/VAN-504
> Add optimizely progressive profiling 1 experiment

- src/register/RegistrationPage.jsx
- src/welcome/WelcomePage.jsx
Control: send optimizely event for optional field only if user has successfully registered and has chosen a value for the option
Variation: send optimizely event for optional field only if user has successfully submitted the progressive profile and has chosen a value for the option
> Update optional field event

- src/common-components/messages.jsx
- src/forgot-password/ForgotPasswordPage.jsx
1. The submit state of the button on Forgot Password Form is updated.
2. A typo is addressed on Landing page
https://openedx.atlassian.net/browse/VAN-524
https://openedx.atlassian.net/browse/VAN-521
After shipping this change to staging and production environment, a user can experience a consistent behavior while submission on Register and Forgot Password Forms.
> update submit button state

- src/forgot-password/ForgotPasswordPage.jsx
- src/reset-password/ResetPasswordPage.jsx
- On forgot password page clear email field error state on focus event.
- On reset password page clear error state of field only which has focused in.
VAN-505
> fix: Clear error state on focus

- src/login/LoginFailure.jsx
- Fix login with inactive user account credentials show alert message on top of the form instead page not found .
- Remove bullet points from failure alert messages on Login page.
VAN-532
> fix: Login page failure alert message

- src/register/CountryDropdown.jsx
Following issues identified in Product review are fixed:
1. I land on page and there is a autopopulated country ‘Pakistan’; when I focus in and press ‘Delete’ from keyboard; it does not delete the last character of the selected country; when I press ‘Delete’ the second time; then it successfully deletes the last character.
2. When i enter characters in the typeahead; it filters dropdown options;  i focus out of field and then i focus in again on the field and it dhows all countries instead of filtered countries for what i enetered.
3. When i click on arrow icon on the right; it open dropdown and shows all countried; it should show only filtered countries; when i click again on the arrow icon; it does not close the dropdown.
> fix issues in typeahead

- package-lock.json
- package.json
- src/forgot-password/ForgotPasswordPage.jsx
- src/login/AccountActivationMessage.jsx
- src/login/LoginPage.jsx
- src/login/tests/LoginPage.test.jsx
- src/register/RegistrationPage.jsx
- src/register/tests/RegistrationPage.test.jsx
- src/reset-password/ResetPasswordPage.jsx
Updated paragon version to use latest stateful buttons that have a default pending icon. 
Ticket: [VAN-497](https://openedx.atlassian.net/browse/VAN-497)
> refactor: update stateful buttons

- src/register/RegistrationPage.jsx
- src/register/tests/RegistrationPage.test.jsx
If a user enters “edx” (already registered username) they will receive the below suggestion. This is the correct behaviour.
If the user then clears their entry and types “b”, they receive the suggestions from their previous entry:
We are already clearing username field error on field focus we just need to clear username suggestions as well.
https://openedx.atlassian.net/browse/VAN-603
> fix: clear username suggestion of field focus

- src/redesign/login/LoginFailure.jsx
- src/redesign/login/messages.jsx
- src/redesign/login/tests/LoginFailure.test.jsx
- Fixed a few typos in the login failure messages
- Updated messages to be inside paragraphs instead of being separated by line breaks. 
Ticket: https://openedx.atlassian.net/browse/VAN-612
> fix typos in login failure messages

- src/redesign/_style.scss
- src/redesign/common-components/PasswordField.jsx
- set password field icon size according to figma design.
**Before:**
**After:**
VAN-523
> fix: Password field icon size

- src/redesign/register/RegistrationPage.jsx
- src/redesign/register/data/constants.js
- src/redesign/register/utils.js
context:
Following are the issues reported by Jon after verification:
Input | Expected result | Actual result
-- | -- | --
jon@protonmail.com | No warning or suggestion | Warning + jon@hotmail.com
jon@aol.com | No warning or suggestion | Warning + jon@yahoo.com
jon@harvard.fas.edu|No warning or suggestion|Error + jon@harvard.as
The fix removes these issue ^
- Added a check to ignore email addresses with multiple subdomains
- Updated suggestion for valid email addresses with no service and tld suggestions to use edit distance of 3 instead of 4(default)
Ticket: https://openedx.atlassian.net/browse/VAN-598
> VAN-598: update email warnings and errors

- src/redesign/_style.scss
- fix start learning with edx text overlapping over logo.
**Before**
**After**
VAN-606
> fix: fix overlapping over logo

- src/redesign/_style.scss
- src/redesign/common-components/InstitutionLogistration.jsx
- src/redesign/common-components/Logistration.jsx
- update SAML page style according to figma style.
**After Fix:**
SAML link
SAML Page
**Figma Design:**
https://www.figma.com/file/0uBm1o7nH2ExePrRXGvB7Z/Logistration?node-id=1018%3A12582
**How to test locally:**
- set `DISABLE_ENTERPRISE_LOGIN=true` in `.env.development`.
- restart node server.
VAN-64
> fix: login/register SAML page style

- src/register/RegistrationPage.jsx
During Login to Register tab switch, optimizely page event is not fired. It is only fired when page is reloaded, in order to fix that we have called the page event manually.
> fix: activate optimizely event manually

- src/_style.scss
> fix: header text for Spanish

- src/common-components/SocialAuthProviders.jsx
- src/common-components/tests/__snapshots__/SocialAuthProviders.test.jsx.snap
A brand name *Apple* should not be translated when page language changes. I have fix it in this PR.
[https://openedx.atlassian.net/browse/VAN-717](https://openedx.atlassian.net/browse/VAN-717)
Here is the attached Video:
https://user-images.githubusercontent.com/7627421/133074896-4e43e51e-a07f-44e6-aab7-37bc2ebf0583.mov
> fix: SSO *Apple* translated in authn pages.

- src/register/data/constants.js
Remove the Confusion for any new users who still have an msn.com email address.
> fix: remove aol domain from email provider list

- src/data/constants.js
- src/register/RegistrationPage.jsx
- src/register/tests/RegistrationPage.test.jsx
- fire track event for save for latter course.
- event will fire when user click on enroll button in email template.
**This PR depends on:**
https://github.com/edx/edx-platform/pull/29089
VAN-741
> feat: fire track event

- src/login/AccountActivationMessage.jsx
- src/login/messages.jsx
- src/login/tests/AccountActivationMessage.test.jsx
- src/login/tests/LoginPage.test.jsx
- src/register/messages.jsx
As part of removing account activation step, we have repurposed the account activation email to account verification email. Following PR updates the success, error and information messages once the link has been clicked given in the email.
||Success|Info|Error|
|----|----|----|----|
OLD|<img width="780" alt="Screenshot 2021-11-10 at 5 19 44 PM" src="https://user-images.githubusercontent.com/40633976/141293546-f8e68624-9a8e-4f1c-adfa-2a9ade15bf89.png">|<img width="780" alt="Screenshot 2021-11-10 at 5 20 04 PM" src="https://user-images.githubusercontent.com/40633976/141293562-d29a79dc-6282-49b7-9c35-feb2714b764d.png">|<img width="780" alt="Screenshot 2021-11-10 at 5 19 56 PM" src="https://user-images.githubusercontent.com/40633976/141293557-eb73a09c-4404-469a-a236-924017bbbc2e.png">| …
> refactor: update account verification messages

- Makefile
- package-lock.json
- package.json
- src/login/messages.jsx
As of April 7th, 2022 the API versions 2 and 2.5 will no longer be operational and relevant requests will begin to fail. Switched to `@edx/reactifex` from `reactifex` which does support V3.
VAN-894
> chore: update transifex scripts to api v3

- src/reset-password/ResetPasswordPage.jsx
The spinner that appears on the `Password Reset Page` should be centred aligned
|Before|After|
|-------|------|
> fix: password reset page spinner position

- src/_style.scss
Text fit in login button
VAN-889
> fix: button width

- src/_style.scss
The Cross icon was overlapping the border of the username field when username suggestions were generated,
This PR fixes the position of the cross icon of username suggestions field
[VAN-936](https://openedx.atlassian.net/browse/VAN-936)
**Before**
**After**
> fix: Update position of cross icon on username field

- src/_style.scss
The trailing element in a field is out of position in some browsers that do not support `inset-inline-end` property such as Safari version 13 and less. This PR fixes this problem for all browsers
**Before**
**After**
> fix: Styling issue in fields trailing element

- .github/workflows/lockfileversion-check.yml
lockfileVersion for the package-lock.json generated by NPM6 was 1 but now as we've moved to Node16 and NPM8, package-lock.json should be generated using NPM8. lockfileVersion for package-lock.json generated using NPM8 is 2. So here we're going to check the lockfileVersion in package-lock.json
> feat: Add check for package-lock file version

- src/forgot-password/ForgotPasswordPage.jsx
- src/forgot-password/data/actions.js
- src/forgot-password/data/reducers.js
- src/forgot-password/data/tests/reducers.test.js
- src/forgot-password/data/tests/sagas.test.js
- src/forgot-password/tests/ForgotPasswordPage.test.jsx
- src/login/LoginPage.jsx
- src/login/data/actions.js
- src/login/data/reducers.js
- src/login/data/selectors.js
- src/login/data/tests/reducers.test.js
- src/login/data/tests/sagas.test.js
- src/login/tests/LoginPage.test.jsx
- src/register/RegistrationPage.jsx
- src/register/data/actions.js
- src/register/data/reducers.js
- src/register/data/selectors.js
- src/register/data/tests/reducers.test.js
- src/register/data/tests/sagas.test.js
- src/register/tests/RegistrationPage.test.jsx
**Before:**
When the user switched tab between the Register page, Login page, and ForgotPassword page, the entered data in the forms was lost
**After:**
Data entered in any of the forms is persisted on the switching tab between the Register page, Login page, and ForgotPassword page.
[VAN-618](https://2u-internal.atlassian.net/browse/VAN-618)
**Demonstration**
https://user-images.githubusercontent.com/52817156/170024175-ce8bc1ab-5eba-46c7-9f90-208b20c2a0bb.mov
> fix: Persist Register/Sign in form states on tab switch [VAN-618]

- src/base-component/AuthExtraLargeLayout.jsx
- src/base-component/AuthMediumLayout.jsx
- src/base-component/AuthSmallLayout.jsx
- src/base-component/LargeLeftLayout.jsx
- src/base-component/MediumLayout.jsx
- src/base-component/SmallLayout.jsx
The decorative image on /login, /register, and /reset page was taking focus on IE11
[VAN-510](https://2u-internal.atlassian.net/browse/VAN-510)
> fix: decorative image takes focus

- src/_style.scss
- src/common-components/PasswordField.jsx
Password tooltip should use an extra small font size of 12px.
[VAN-577](https://2u-internal.atlassian.net/browse/VAN-577)
**Before**
**After**
> fix: password tooltip should use extra small font size

- src/_style.scss
- src/common-components/messages.jsx
Password tooltip arrow was casting shading on-field border making it look disconnected and the letters should be lowercase in the tooltip.
[VAN-585 ](https://2u-internal.atlassian.net/browse/VAN-585)
**Before**
**After**
> fix: password popover rendering issue [VAN-585]

- src/register/RegistrationPage.jsx
- src/register/tests/RegistrationPage.test.jsx
Users are not enrolled in course when creating an account. If they come to authn from the course about page by clicking enroll button, they should redirect to enrollment view after successfully registering with us. 
The next url is missing in our payload which is required by registration view to generate redirect url:
https://github.com/openedx/edx-platform/blob/af81b3a609d1aa9deb658e130613ac463cb48f2e/common/djangoapps/student/helpers.py#L346
Ticket: https://2u-internal.atlassian.net/browse/VAN-1018
> feat: add query params to the payload

- src/_style.scss
This PR fixes the warning that was being raised on the password field popover.
**Before:**
**After:**
> fix: warning on password field popover margin

- src/_style.scss
> fix: [VAN-628] Google logo is centrally aligned.

- src/common-components/FormGroup.jsx
- src/common-components/Logistration.jsx
- src/common-components/PasswordField.jsx
- src/data/constants.js
- src/register/RegistrationFailure.jsx
- src/register/RegistrationPage.jsx
- src/register/data/actions.js
- src/register/data/reducers.js
- src/register/data/selectors.js
- src/register/data/tests/reducers.test.js
- src/register/registrationFields/CountryDropdown.jsx
- src/register/registrationFields/EmailField.jsx
- src/register/registrationFields/HonorCode.jsx
- src/register/registrationFields/TermsOfService.jsx
- src/register/registrationFields/UsernameField.jsx
- src/register/registrationFields/index.js
- src/register/tests/HonorCode.test.jsx
- src/register/tests/TermsOfService.test.jsx
- src/register/utils.js
- src/reset-password/ResetPasswordPage.jsx
- src/sass/_registration.scss
- src/sass/_style.scss
What this PR covers:
- The default registration fields which include:
- name
- email
- username
- password
- On Blur and On Focus events
- Frontend and backend validations for these fields
- Empty form submission error
- Error under the fields
- Error alert over the form 
- Any backend error that occurred when creating a new user
- Persist state for errors and field values on tab switch
What this PR **doesn't** cover:
- Failing tests are not catered in this ticket. There is a separate ticket for it.
- Any lint errors related to imports are not fixed.
- Successful creation of user account. This will be covered once we add dynamic fields (which includes the country and honor code fields).
- Redirection is not covered in this PR
Ticket: https://2u-internal.atlassian.net/browse/VAN-1069
> feat: add basic registration form

- src/sass/_base_component.scss
* Adds RTL support to skewed rectangle transformation 
* With this fix, the skew transformation becomes tilted to the right in LTR and to the left in RTL.
* All screen sizes are covered by this fix
When using the authentication MFE in an RTL language (Arabic for instance), the tilted line  separating  the "Start Learning with <platform name>" block from the page forms is not rendered correctly
Faulty layout in RTL
Fixed layout in RTL
> RTL: Fix skewed and slanted graphics

- .github/workflows/ci.yml
- package-lock.json
- package.json
- Removes custom browserslist configuration in favor of using a [shared configuration](https://github.com/edx/browserslist-config).
- Removes is-es5 check in CI. The purpose of ES5 check was to verify that the built code is compatible with older browsers like IE 11. However, we’re now no longer supporting IE 11.
> build: use shared browserslist configuration

- src/sass/_base_component.scss
- src/sass/_style.scss
We currently have branding issue in our repo. We are hardcoding branding colors in different parts of our code.
Now, we are using paragon branding variables instead of hardcoding the colors.
Tickets: [VAN-1163](https://2u-internal.atlassian.net/browse/VAN-1163)
> fix: use paragon branding variables for colors

- src/register/ConfigurableRegistrationForm.jsx
- src/register/RegistrationPage.jsx
- src/register/tests/RegistrationPage.test.jsx
Relying on the outer state causes unexpected issues. During set state, use the react's internal state to refer to previous values.
> fix: update set state functions to use prevState

- src/welcome/ProgressiveProfiling.jsx
Fix that progressive profiling page to stop showing the optional field error and also Verify twelcome page is not accessible when directly hit from the browser.
|Before|After|
> fix: add proper error handling for progressive profiling page.

- src/welcome/ProgressiveProfiling.jsx
By setting the global state null history will be clear and the user will again redirected to the dashboard instead progressive profile page.
VAN-1214
> fix: unable to resubmit form

- src/common-components/RedirectLogistration.jsx
- src/common-components/data/reducers.js
- src/common-components/data/tests/reducer.test.js
- src/progressive-profiling/ProgressiveProfiling.jsx
- src/register/RegistrationPage.jsx
Description
frontend-platform's ensureAuthenticatedUser was throwing exceptions in case of the unauthenticated user along with redirecting to the login page. This PR passes that exception.
Why it was reverted earlier? 
I had extended_profile configuration set to string instead it should be set to an array. So in code, I was converting string to an array which was not needed actually and was causing exception. which is resolved now.
[VAN-1224](https://2u-internal.atlassian.net/browse/VAN-1224)
> fix: uncaught exception on progressive profiling

- src/common-components/data/reducers.js
On login page we do not get additional fields in the MFE context. When the login page tries to get the third party auth context it gives error because `extendedProfile` is undefined.
```javascript
TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at reducer (reducers.js?73fe:28:43)
at combination (redux.js?00d8:560:1)
at M (<anonymous>:1:32997)
at z (<anonymous>:1:33284)
at <anonymous>:1:36378
at Object.dispatch (redux.js?00d8:288:1)
at e (<anonymous>:1:37227)
at eval (redux-logger.js?d665:1:7805)
at eval (redux-saga-core.esm.js?42a9:1410:1)
```
Tested the changed locally
> fix: sso button not appearing on login page

- src/common-components/data/reducers.js
- src/common-components/data/selectors.js
- src/common-components/data/tests/reducer.test.js
- src/register/RegistrationPage.jsx
- src/register/registrationFields/HonorCode.jsx
- src/register/registrationFields/TermsOfService.jsx
- src/register/tests/HonorCode.test.jsx
- src/register/tests/TermsOfService.test.jsx
[VAN-1231](https://2u-internal.atlassian.net/browse/VAN-1230)
removed unused extendedProfile object from the registration page and added space before the honor code and TOS link.
Tested locally by registering with additional registration and optional fields and checking if they are saved correctly at the backend.
> fix: update MFE context

- src/register/RegistrationPage.jsx
- src/register/tests/RegistrationPage.test.jsx
There is a case when an undefined converting to object, fixed that issue.
Ticket: [VAN-1249](https://2u-internal.atlassian.net/browse/VAN-1249)
> fix: Progressive Profiling can't convert undefined to object

- public/index.html
Customize the Zendesk Web Widget in authn for edX support for bootcamp.
Learners on the rest of the courses have no access to BootCamp Support unless they are in the Bootcamp Course.
<table>
<tr>
<td>
<h4>Before</h4>
</td>
<td>
<h4>After</h4>
</td>
</tr>
</table>
**How to test locally:**
1. Set up `ZENDESK_KEY` and `ZENDESK_LOGO_URL` in `env.development`
2. Up the server
3. You will find it on authn
Ticket [link](https://2u-internal.atlassian.net/browse/VAN-1290)
> fix: Customiz Zendesk

- public/index.html
A closing bracket was missing in zen-desk settings.
> fix: syntext error fixed

- src/forgot-password/ForgotPasswordPage.jsx
- src/forgot-password/tests/ForgotPasswordPage.test.jsx
[This is a backport](https://github.com/openedx/frontend-app-authn/pull/744).
In the EdX community, support pages are not created in all instances. In this case, links to the support page are always displayed in certain places. The forgot password page has a button **"Need help signing in?"**. Currently, it is impossible to disable this button without removing it. I suggest adding the ability to automatically show or hide this button depending on whether there is a link to the support page in the configuration file (the link is added in LOGIN_ISSUE_SUPPORT_LINK).
**if a link to a support page exists**
**if the link to the support page does not exist**
> feature: don't show support button if it is not used

- src/login/LoginPage.jsx
- src/login/tests/LoginPage.test.jsx
A case was found when providers were displayed in authentication and there was no header for this block **"Or sign in with"**.
This case occurred when there was such a combination [in this condition](https://github.com/openedx/frontend-app-authn/blob/ee6a6f0d2d60b41a677f4efa3f2942251aa37754/src/login/LoginPage.jsx#L173): **isEnterpriseLoginDisabled=true** (DISABLE_ENTERPRISE_LOGIN=true), **isSocialAuthActive=true** (Providers have been configured in admin), **isInstitutionAuthActive=false** (secondary Providers are not configured), currentProvider="" (current provider no selected).
I picked a combination that would allow displaying this title whenever this block exists. And also wrote tests for all these cases.
**DISABLE_ENTERPRISE_LOGIN=true, Providers=not configured, …
> feat: Fixed missing "Or sign in with" display in some cases

- src/login/LoginPage.jsx
- src/login/tests/LoginPage.test.jsx
This is a [backport](https://github.com/openedx/frontend-app-authn/pull/749).
A case was found when providers were displayed in authentication and there was no header for this block **"Or sign in with"**.
This case occurred when there was such a combination [in this condition](https://github.com/openedx/frontend-app-authn/blob/ee6a6f0d2d60b41a677f4efa3f2942251aa37754/src/login/LoginPage.jsx#L173): **isEnterpriseLoginDisabled=true** (DISABLE_ENTERPRISE_LOGIN=true), **isSocialAuthActive=true** (Providers have been configured in admin), **isInstitutionAuthActive=false** (secondary Providers are not configured), currentProvider="" (current provider no selected).
I picked a combination that would allow displaying this title whenever this block exists. And also wrote tests for all these cases. …
> fix: display or sign in with

- src/recommendations/RecommendationsPage.jsx
- src/sass/_recommendations_page.scss
Bottom padding was missing the unit. 
Ticket: https://2u-internal.atlassian.net/browse/VAN-1324
|Before|After|
| <img width="770" alt="Screenshot 2023-03-01 at 5 28 27 PM" src="https://user-images.githubusercontent.com/40633976/222140282-5708b403-7b3c-4a2f-b9d4-66385694dc2b.png">|<img width="770" alt="Screenshot 2023-03-01 at 5 57 07 PM" src="https://user-images.githubusercontent.com/40633976/222145802-f11d0060-474c-41bb-a2b4-17a455ef196b.png">
|
> fix: bottom padding missing unit

- src/login/LoginFailure.jsx
This PR is a backport from the [master](https://github.com/openedx/frontend-app-authn/pull/752).
The community EdX uses two deployment paths: using a different subdomain for each MFE (for example https://authn.edx.org/) and using one domain for each MFE, but adding the first path element with the name of this MFE (for example https://app-mfe.company.com/authn/). 
When using two different deployment approaches, with one of them we get an incorrectly working link to the password reset page.
In the first case, the transition is performed correctly, when you navigate from the https://authn.edx.org/login page to the https://authn.edx.org/reset page. But, in the second case, there is a transition from the https://app-mfe.company.com/authn/login page to the https://app-mfe.company.com/reset …
> fix: incorrect link to password reset page

- src/sass/_style.scss
A horizontal scrollbar was detected on the Windows platform, which caused the close button for the cookies banner to become invisible.
We found this commit - https://github.com/openedx/frontend-app-authn/pull/393 and after removing code from this PR - problem was solved. Maybe in the past it was correct fix, but as for now - we think that it's no need. After removing this code we tested login and registration page on all browsers in windows, mac and linux - and all ok. Horizontal scrollbar disappeared. And we couldn't find any problems, mentioned in this commit https://github.com/openedx/frontend-app-authn/pull/393
We found commit https://github.com/openedx/frontend-app-authn/pull/393, and after removing the code from this PR, the problem was solved. Perhaps in the past, it was the …
> fix: Remove horizontal scroll in windows (olive branch)

- src/welcome/ProgressiveProfiling.jsx
- src/welcome/tests/ProgressiveProfiling.test.jsx
This is the [backport from the master](https://github.com/openedx/frontend-app-authn/pull/762)
Not everyone in the community uses page support. This update adds the dependence of the link display on the welcome page on the presence of a non-empty variable WELCOME_PAGE_SUPPORT_LINK in the MFE settings.
By default `WELCOME_PAGE_SUPPORT_LINK='http://localhost:1999/welcome'`
If WELCOME_PAGE_SUPPORT_LINK is empty:
If the WELCOME_PAGE_SUPPORT_LINK variable contains the address of the support page:
> feat: displaying a support link on the welcome page

- src/progressive-profiling/ProgressiveProfiling.jsx
- src/progressive-profiling/tests/ProgressiveProfiling.test.jsx
This pull request addresses an issue where user_ids are missing from welcome page events due to an in-page redirect. Now, capturing user_id after registration by making a segment identify call.
Ticket: [VAN-1262](https://2u-internal.atlassian.net/browse/VAN-1262)
> fix: make identify call to pass missing user_id

- src/register/registrationFields/CountryField.jsx
VAN-1317
On Safari browser country dropdown field is not functional so we have added the onMuseDown event for default prevention.
> fix: country dropdown issue on safari

- src/common-components/EnterpriseSSO.jsx
- src/common-components/Logistration.jsx
- src/common-components/messages.jsx
- src/common-components/tests/Logistration.test.jsx
- src/login/tests/LoginPage.test.jsx
Hides Signup page and “Login/Register” tab when ALLOW_PUBLIC_ACCOUNT_CREATION is False.
> feat: hide signup page on the bases of flag

- src/progressive-profiling/messages.jsx
Update the browser title for the progressive profiling page on Authn.
|Before|After|
|<img width="1397" alt="Screenshot 2023-03-20 at 4 50 51 PM" src="https://user-images.githubusercontent.com/7627421/226332924-2e2b589d-0e7f-4ed7-b6fb-0c4d09c3a37b.png">|<img width="1317" alt="Screenshot 2023-03-20 at 4 50 31 PM" src="https://user-images.githubusercontent.com/7627421/226332940-12b657b5-e885-48a0-94b0-922bd6d03dd7.png">|
> fix: Update the browser title for progressive profiling page

- src/progressive-profiling/ProgressiveProfiling.jsx
- src/recommendations/RecommendationsPage.jsx
This PR fixes two anomalies with welcome page recommendations viewed event
1. Recommendations viewed event was being sent two times for original variation (one without user id and one with user id)
2. Recommendations viewed event was not having course keys for experiment variation
Tested locally
> fix: fix recommendations viewed event count anomly

- package-lock.json
- package.json
The purpose of this pull request is to downgrade the **frontend-platform** version from `3.6.1` to `3.6.0`, as described in this [PR](https://github.com/openedx/frontend-platform/pull/462)
> chore: downgrade frontend-platform version from 3.6.1 to 3.6.0

- src/common-components/SocialAuthProviders.jsx
- src/common-components/tests/__snapshots__/SocialAuthProviders.test.jsx.snap
A change made in https://github.com/openedx/frontend-app-authn/pull/791 changed the SSO button position. The PR fixes it.
[VAN-1347](https://2u-internal.atlassian.net/browse/VAN-1347)
Updated snapshot tests
|Before|After|
|<img width="496" alt="Screenshot 2023-03-31 at 2 24 42 PM" src="https://user-images.githubusercontent.com/40633976/229081587-4fbefcd9-0fb6-4dfb-a8b2-832fc81e09aa.png">|<img width="496" alt="Screenshot 2023-03-31 at 2 24 59 PM" src="https://user-images.githubusercontent.com/40633976/229081595-b5001a80-d67a-4673-84b5-d448b0dd61b2.png"> |
> fix: sso providers position

- src/setupTest.js
- Remove console log warnings from SocialAuthProviders unit tests by mocking the location object.
- Mock localStorage.
VAN-1350
> fix: window console warning

- src/common-components/Logistration.jsx
- src/common-components/RedirectLogistration.jsx
- src/common-components/SocialAuthProviders.jsx
- src/common-components/data/actions.js
- src/common-components/data/reducers.js
- src/common-components/data/tests/reducer.test.js
- src/common-components/tests/Logistration.test.jsx
- src/common-components/tests/SocialAuthProviders.test.jsx
- src/login/LoginFailure.jsx
- src/login/LoginPage.jsx
- src/login/data/constants.js
- src/login/messages.jsx
- src/login/tests/LoginFailure.test.jsx
- src/login/tests/LoginPage.test.jsx
- src/register/RegistrationFailure.jsx
- src/register/RegistrationPage.jsx
- src/register/data/constants.js
- src/register/data/utils.js
- src/register/messages.jsx
- src/register/tests/RegistrationPage.test.jsx
This PR adds a fix to render tpa authentication error on frontend that was not handled before.
[VAN-1339](https://2u-internal.atlassian.net/browse/VAN-1339)
Tested locally by raising errors through social and SAML auth
|Legacy behavior|Authn Behaviour Now (If TPA error occurs on register page)|Authn Behaviour Now (If TPA error occurs on login page)|
|-------|---------|--------|
> fix: render tpa pipeline error from django messages on mfe

- src/register/RegistrationPage.jsx
We are auto-submitting the registration form when skip_registeration_form is true and while submitting we get displayValue attribute of the country field which is set only when the country code is coming from the backend or the user set the country from the field.
But in the case when auto submitting and country code not coming, this attribute is not set which causes an exception.
Tested locally
\
> fix: ripple effect of skip_registeration_form if country code is empty

- src/progressive-profiling/ProgressiveProfiling.jsx
This pull request resolves an issue where user_ids were missing from welcome page events because of an in-page redirect. To fix this, we are now capturing user_ids after registration by making a segment identify call.
Ticket: [VAN-1262](https://2u-internal.atlassian.net/browse/VAN-1262)
> fix: issue of missing user_id on welcome page events

- src/common-components/data/service.js
Since the `mfe_context` API response now uses camelCase instead of snake_case, the `camelCaseObject` method is no longer necessary and we can use the new camelCase keys directly in the front-end. Therefore, this PR modifies the keys used in the `mfe_context` API response accordingly.
Related Ticket: [VAN-1311](https://2u-internal.atlassian.net/browse/VAN-1311)
> Backend [PR](https://github.com/openedx/edx-platform/pull/31930)
> fix: change keys to camelCase for mfe_context response

- .eslintrc.js
- src/register/data/constants.js
- src/register/registrationFields/CountryField.jsx
- src/register/tests/RegistrationPage.test.jsx
We were using nested components inside the the CountryField. Creating components inside components (nested components) will cause React to throw away the state of those nested components on each re-render of their parent. The reference to the same element changes on each re-render when defining components inside the render block. This leads to complete recreation of the current node and all its children. As a result the virtual DOM has to do extra unnecessary work.
[VAN-1358](https://2u-internal.atlassian.net/browse/VAN-1358)
- Tested locally
- Running the unit tests
> fix: nested components in CountryField

- .github/workflows/autoupdate-pull-request.yml
Description
Remove conditional logic from autoupdate label as it does not run on master push
It will be tested on remotely 
Related to: https://2u-internal.atlassian.net/browse/VAN-1349
> fix: remove conditional logic

- package-lock.json
- package.json
VAN-1380
`react-onclickoutside` was used in country dropdown field to catch outside click and close the dropdown but we changed its implementation and use onBlur event for this now therefore it is not needed anymore and can be removed.
PR in which it was added: https://github.com/openedx/frontend-app-authn/commit/5358538d2212d280b4694bf83505500d1042db6f
[VAN-1380](https://2u-internal.atlassian.net/browse/VAN-1380)
Tested locally
> chore: remove react-onclickoutside package

- package-lock.json
- package.json
VAN-1381
`sanitize-html` was a dependency to `@edx/paragon` which was not directly used in `frontend-app-authn` but it was pinned to fix security vulnerabilities in authn in this [PR](https://github.com/openedx/frontend-app-authn/pull/514/files).
By `v16.0.0` of `@edx/paragon`, they have removed the dependency of `sanitize-html` and is not used anymore (https://github.com/openedx/paragon/releases/v16.0.0).
and as we are not using `v16.0.0` of `@edx/paragon` (we are on latest version), we can remove it from authn as well.
[VAN-1381](https://2u-internal.atlassian.net/browse/VAN-1381)
Tested locally
> chore: remove sanitize-html package

- src/common-components/EnterpriseSSO.jsx
- src/common-components/SocialAuthProviders.jsx
- src/common-components/tests/__snapshots__/SocialAuthProviders.test.jsx.snap
- src/login/tests/LoginPage.test.jsx
- src/register/tests/RegistrationPage.test.jsx
Currently, the faSignInAlt icon from fontawesome is being used in authn, but we want to replace it with a Paragon icon to provide a more consistent experience.
https://2u-internal.atlassian.net/browse/VAN-1375
|Before|After|
> fix: replace faSignInAlt with paragon icon

- package-lock.json
- package.json
`semver-regex` was a dependency to `"@edx/frontend-build"` which was not directly used in `frontend-app-authn` but it was pinned to fix security vulnerabilities in authn in this [PR](https://github.com/openedx/frontend-app-authn/pull/514/files).
The` semver-regex` was a dependency to `image-webpack-loader` which was replaced with `image-minimizer-webpack-plugin` hence removing semver-regex along with other dependencies of image-webpack-loader therefore it's no longer a concern. This security vulnerability is fixed in this PR https://github.com/openedx/frontend-build/pull/259/files#diff-053150b640a7ce75eff69d1a22cae7f0f94ad64ce9a855db544dda0929316519L16092
We are on latest version `@edx/frontend-build": "12.8.10`  we can remove it from authn as well. …
> chore: remove semver-regex package

- .eslintrc.js
- src/MainApp.jsx
- src/common-components/index.jsx
- src/logistration/Logistration.jsx
- src/logistration/Logistration.test.jsx
VAN-1388
A recent [change](https://github.com/openedx/frontend-app-authn/pull/791) updated the version of `eslint-plugin-import` form `2.26.0 -> 2.27.5`
This change resulted in an `import/no-cycle error` linting error which is fixed in this PR.
**How this is fixed?**
We have a `common-components` directory containing components which are used by all other components in `frontend-app-authn`. The `Logistration` component was in `common-components` and it imports the `Login` and `Register` Pages. Inside the login and register pages, we are importing other components from `common-components` which caused an `import-cycle` dependency issue in authn. 
This PR moved the `Logistration` component from common components to a separate container. …
> fix: import/no-cycle eslint issue

- package-lock.json
- package.json
Remove unused package extract-react-intl-messages from package.json, this package was used to translate the messages and started using different one so we can safely remove it. We have opted to use @edx/reactifex for translations. 
PR in which this package was added. [b42ca99](https://github.com/openedx/frontend-app-authn/commit/b42ca9917680876b222990822d93d5583eb0a32e)
Locally 
Related to: https://2u-internal.atlassian.net/browse/VAN-1378
> fix: remove extract-react-intl-messages

- src/sass/_style.scss
This is the copy of https://github.com/openedx/frontend-app-authn/pull/759
A horizontal scrollbar was detected on the Windows platform, which caused the close button for the cookies banner to become invisible. 
We found this commit - https://github.com/openedx/frontend-app-authn/pull/393 and after removing code from this PR - problem was solved. Maybe in the past it was correct fix, but as for now - we think that it's no need. After removing this code we tested login and registration page on all browsers in windows, mac and linux - and all ok. Horizontal scrollbar disappeared. And we couldn't find any problems, mentioned in this commit https://github.com/openedx/frontend-app-authn/pull/393
We found commit https://github.com/openedx/frontend-app-authn/pull/393, and after removing the code …
> fix: Remove horizontal scroll in windows (master branch)

- package-lock.json
- package.json
`fortawesome/free-regular-svg-icons ` package which is not used in the `frontend-app-authn` but was pinned in this initial commit https://github.com/openedx/frontend-app-authn/commit/d5cdbcb4b6569baa67fd6b2d2167303cf9f3b94c
[VAN-1377](https://2u-internal.atlassian.net/browse/VAN-1377)
Tested locally
> chore: remove fortawesome/free-regular-svg-icons package

- src/common-components/data/service.js
This PR removes the launch strategy logic code that was implemented to prevent the front-end from breaking while serializing the MFE context API response to camelCase on the back-end. Since both the front-end and back-end PRs have been deployed on production, the launch strategy logic code is no longer necessary.
> Related Ticket: [VAN-1311](https://2u-internal.atlassian.net/browse/VAN-1311)
> fix: eliminate the usage of OR operator in MFE context API

- Makefile
- src/i18n/index.jsx
- src/index.jsx
feat: use `atlas` in `make pull_translations`
Changes
-------
- Move all i18n imports into `src/i18n/index.js` so `intl-imports.js` can    override it with latest translations
- Add `atlas` into `make pull_translations` when `OPENEDX_ATLAS_PULL` environment variable is set.
Testing
-------
**Note:** I had to disable the Third-Party Auth form since it didn't work for me even on `master`.
References
----------
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which is sparked by the [Translation Infrastructure update OEP-58](https://open-edx-proposals.readthedocs.io/en/latest/architectural-decisions/oep-0058-arch-translations-management.html#specification).
Up-to-date project overview and details are available in the [Approach Memo and Technical …
> feat: use `atlas` in `make pull_translations`

- src/common-components/Zendesk.jsx
- src/common-components/tests/__snapshots__/Zendesk.test.jsx.snap
Description:
Add departments list in Zendesk widget configurations
Related to: [VAN-1426](https://2u-internal.atlassian.net/browse/VAN-1426)
How it has been tested?
This is tested locally.
Before adding the departments:
After adding the departments:
> fix: add departments in Zendesk widget

- src/register/registrationFields/CountryField.jsx
- src/register/tests/RegistrationPage.test.jsx
VAN-1415
This PR fixed a bug in the country field.
**Bug:** 
Validations were being run when drop-down arrow was clicked. Which should not run.
[VAN-1415](https://2u-internal.atlassian.net/browse/VAN-1415)
Include a link to the sandbox for design changes or screenshots before and after.
**Before**
https://github.com/openedx/frontend-app-authn/assets/52817156/8ce60555-3007-4408-8eaf-3d4d491cada3
**After**
https://github.com/openedx/frontend-app-authn/assets/52817156/b053725f-39ec-4025-97b0-02872819fd4d
> fix: bugs in country field

- src/login/tests/LoginPage.test.jsx
- src/register/tests/RegistrationPage.test.jsx
A recent change made in this PR: [fix: replace faSignInAlt with paragon icon (#863) · openedx/frontend-app-authn@44cec76](https://github.com/openedx/frontend-app-authn/commit/44cec762fb855f0f77b2e4859bf4b137832add0d) has introduced console errors for the register and login page tests.
[VAN-1428](https://2u-internal.atlassian.net/browse/VAN-1428)
It has been tested locally and also no console error related to the icon exists in this test [build](https://github.com/openedx/frontend-app-authn/actions/runs/4993363761/jobs/8942373708?pr=909)
> fix: fix console error in login and register's test

- src/common-components/RedirectLogistration.jsx
- src/data/constants.js
- src/register/RegistrationPage.jsx
- src/register/tests/RegistrationPage.test.jsx
Description
Redirect the user to welcome page after registration, as Authn is embedded in iframe which is located in Hubspot so we call window.postMessage function from Authn which let the Hubspot knows about redirect URL and then reload the welcome page in parent window.
[VAN-1474](https://2u-internal.atlassian.net/browse/VAN-1474)
> fix: redirect user to welcome page  (#939)

- src/register/ConfigurableRegistrationForm.jsx
- src/register/RegistrationPage.jsx
- src/register/tests/RegistrationPage.test.jsx
Description:
When Authn is embedded in iframe then validations should not runs on blur event it should only run when button is clicked.
Its related to : [VAN-1481](https://2u-internal.atlassian.net/browse/VAN-1481)
Its has been tested locally.
> fix: avoid validations on blur event

- src/MainApp.jsx
- src/common-components/EmbeddedRegistrationRoute.jsx
- src/common-components/RedirectLogistration.jsx
- src/common-components/UnAuthOnlyRoute.jsx
- src/common-components/index.jsx
- src/common-components/tests/EmbeddedRegistrationRoute.test.jsx
- src/common-components/tests/UnAuthOnlyRoute.test.jsx
- src/data/constants.js
- src/data/utils/dataUtils.js
- src/data/utils/index.js
- src/logistration/Logistration.jsx
- src/logistration/Logistration.test.jsx
- src/progressive-profiling/ProgressiveProfiling.jsx
- src/register/RegistrationPage.jsx
This PR updates the embedded registration rendering from the `?variant=embedded` query param to the `/register-embedded` path.
|Before|After|
> fix: render embedded experience through pathname

- src/register/RegistrationPage.jsx
- src/register/tests/RegistrationPage.test.jsx
For the embedded registration form experience even though we do not want to show error on blur we still want to keep the username suggestions that are fetched on the "name" field on blur event. 
[VAN-1498](https://2u-internal.atlassian.net/browse/VAN-1498)
**Don't show error on blur for empty "name" field** 
https://github.com/openedx/frontend-app-authn/assets/40633976/56a30c64-3712-4fa1-af1c-fe4dfa7826c8
**Don't show error on blur for invalid "name" field**
https://github.com/openedx/frontend-app-authn/assets/40633976/88f57239-9aa5-4994-abb5-18ebf69ca7a8
**Show username suggestion**
https://github.com/openedx/frontend-app-authn/assets/40633976/2f86cda3-91e5-4e9c-bb7d-8ee0dfeec61a
> feat: keep username suggestion for origin

- src/progressive-profiling/ProgressiveProfiling.jsx
- src/progressive-profiling/tests/ProgressiveProfiling.test.jsx
- src/register/RegistrationPage.jsx
- src/register/data/actions.js
- src/register/data/sagas.js
- src/register/data/service.js
- src/register/tests/RegistrationPage.test.jsx
Reverts openedx/frontend-app-authn#951
We added this as a debugging event to check if backend event was firing correctly. We have established that it is and we no longer need this event.
> Revert "feat: fire identify call and register event"

- public/index.html
For the embedded experience the privacy banner is appearing twice. We want to hide the one on the form:
I have added a script that runs after 1.5 seconds and hides the banner with class `cc-grower`.
> feat: hide privacy banner for embedded form

- public/index.html
Reverts openedx/frontend-app-authn#954
We no longer need this script because the privacy banner has been set not to show on the `/register-embedded` url using GTM.
> Revert "feat: hide privacy banner for embedded form"

- .env.development
- src/base-container/components/default-layout/index.jsx
- src/base-container/components/image-layout/ExtraSmallLayout.jsx
- src/base-container/components/image-layout/LargeLayout.jsx
- src/base-container/components/image-layout/MediumLayout.jsx
- src/base-container/components/image-layout/SmallLayout.jsx
- src/base-container/components/image-layout/index.jsx
- src/base-container/components/image-layout/index.scss
- src/base-container/components/image-layout/messages.js
- src/base-container/components/welcome-page-layout/LargeLayout.jsx
- src/base-container/components/welcome-page-layout/MediumLayout.jsx
- src/base-container/components/welcome-page-layout/SmallLayout.jsx
- src/base-container/components/welcome-page-layout/index.jsx
- src/base-container/data/constants.js
- src/base-container/index.jsx
- src/config/index.js
- src/register/RegistrationPage.jsx
As part of edx.org rebrand, this PR adds 
- another layout design for Base Container
- optimizely experiment setup for 
I have used [this guide](https://2u-internal.atlassian.net/wiki/spaces/GEM/pages/322699556/Implement+Optimizely+Experiments) for optimizely setup.
[VAN-1506](https://2u-internal.atlassian.net/browse/VAN-1506)
Locally
|Size|With Image|Without Image|
|-------|-----|-------|
| Larger | <img width="768" alt="Screenshot 2023-06-28 at 2 40 40 PM" src="https://github.com/openedx/frontend-app-authn/assets/40633976/30a68d98-9d8a-4fc9-bf8a-2dfb53cda2f7">|<img width="1438" alt="Screenshot 2023-06-28 at 3 35 03 PM" src="https://github.com/openedx/frontend-app-authn/assets/40633976/06abcc42-e1e9-4d31-8d18-13bdfdbf3c09">|
| Medium | <img width="385" alt="Screenshot 2023-06-28 at 2 41 …
> Add image layout for base container

- src/progressive-profiling/ProgressiveProfiling.jsx
The recommendations group event was firing multiple times due to useEffect dependency because registrationResult is setting in the above two useEffects.
[VAN-1569](https://2u-internal.atlassian.net/browse/VAN-1569)
> fix: track event fire multiple times

- src/data/utils/dataUtils.js
In registration embedded experinece, if next Url contains `+`, it gets decoded to ` ` (space) resulting in invalid redirection. This PR fixes this issue.
locally
|Before|After|
> fix: special characters in redirect url getting decoded to space

- src/MainApp.jsx
- src/common-components/RedirectLogistration.jsx
- src/register/EmbeddableRegistrationPage.jsx
- src/register/RegistrationPage.jsx
- src/register/data/utils.js
- src/register/index.js
- src/register/tests/EmbeddableRegistrationPage.test.jsx
- src/register/tests/RegistrationPage.test.jsx
Description:
Adding embedded registration form
[VAN-1574](https://2u-internal.atlassian.net/browse/VAN-1574)
> feat: Add embeddable registration form

- src/register/RegistrationPage.jsx
The register page crashes after clicking on the field "Public username"
How to reproduce: After entering the full name, immediately switch the focus to the "Public username" field.
Getting an error
There is no such error in Palm Release.
> fix: register page crashing after click on field "username"

- src/base-container/index.jsx
- src/common-components/RedirectLogistration.jsx
- src/progressive-profiling/ProgressiveProfiling.jsx
- src/progressive-profiling/tests/ProgressiveProfiling.test.jsx
- src/register/RegistrationPage.jsx
- src/register/data/actions.js
- src/register/data/sagas.js
- src/register/data/service.js
- src/register/data/tests/sagas.test.js
- Removed hydrate authenticated user call from the progressive profiling page and replaced the authenticated user with the details returned by the registration response
- Updated base container to use the username provided by the registration response. Removed extra call for it.
[VAN-1580](https://2u-internal.atlassian.net/browse/VAN-1580)
Updated tests
No design changes in this PR.
> feat: remove hydrate call

- src/recommendations/ProductCard/BaseCard/index.jsx
- src/recommendations/data/utils.js
Fixed issue with subtitle on recommendations card.
[VAN-1657](https://2u-internal.atlassian.net/browse/VAN-1657)
Locally
|Before|After|
|<img width="1004" alt="Screenshot 2023-09-08 at 12 23 27 PM" src="https://github.com/openedx/frontend-app-authn/assets/40633976/b2ad57e6-e449-485c-8253-bada91c64641">|<img width="1440" alt="Screenshot 2023-10-06 at 2 29 47 PM" src="https://github.com/openedx/frontend-app-authn/assets/40633976/54e86965-7aa4-470c-b4df-fca70cb1ef47"><img width="283" alt="Screenshot 2023-10-06 at 2 31 55 PM" src="https://github.com/openedx/frontend-app-authn/assets/40633976/0468e980-c0d7-423d-ab0f-0c5ad5192381">|
> feat: fix recommendations card subtitle

- src/register/data/utils.js
When country is not required to submit, the displayValue check
will always return true. This fixes it by only check it if it's
needed through the config `SHOW_CONFIGURABLE_EDX_FIELDS`
This issue might has been discoverd at edx.org becuase edx.org
requires the Country to be filled when creating an account,
however this is not the case for Open edX by default, hence the
issue reported below
Ref: openedx/wg-build-test-release/issues/318
You would need to locally install tutor and tutor-mfe `quince` branch and then try to recreate an account after all services has been inits. And lastly rebuild the MFE image using my fork as a base and you should then be able to create an account
> fix: form submission when country is not requried

- src/progressive-profiling/ProgressiveProfiling.jsx
- src/progressive-profiling/tests/ProgressiveProfiling.test.jsx
Description:
Add spinner while fetching the optional fields in embedded exp 
[VAN-1658](https://2u-internal.atlassian.net/browse/VAN-1658)
**Before**
https://github.com/openedx/frontend-app-authn/assets/12580995/164a2992-6885-4cf4-9c54-003372710f2e
**After**
https://github.com/openedx/frontend-app-authn/assets/12580995/bf5b09f4-4da7-45e7-bc74-5b5ec25d7e5c
> fix: add spinner while fetching the optional fields in embedded exp

- src/register/RegistrationPage.test.jsx
- src/register/components/ConfigurableRegistrationForm.test.jsx
- src/register/components/RegistrationFailure.test.jsx
- src/register/components/ThirdPartyAuth.test.jsx
All tests that are not directly related to the registration form functionality have been moved to their respective component-specific test files. 
[VAN-1628](https://2u-internal.atlassian.net/browse/VAN-1628)
> fix: moved registration tests to specific files.

- src/i18n/messages/ar.json
- src/i18n/messages/de_DE.json
- src/i18n/messages/es_419.json
- src/i18n/messages/fr.json
- src/i18n/messages/hi.json
- src/i18n/messages/it_IT.json
- src/i18n/messages/pt_PT.json
- src/i18n/messages/ru.json
- src/i18n/messages/uk.json
- src/i18n/messages/zh_CN.json
- src/login/LoginPage.jsx
- src/login/messages.jsx
- src/login/tests/LoginPage.test.jsx
For now, we have the ability to register with a username consisting of 2 characters. However, when we try to log in with this username, we receive an error indicating that the 'username should be at least 3 characters.' In this PR, we fix this bug.
https://github.com/openedx/frontend-app-authn/assets/19806032/66b9b731-f797-4a7c-bb88-48fb34b45b48
https://github.com/openedx/frontend-app-authn/assets/19806032/0a36a6b9-d0e9-4c04-867b-8f91443262c2
https://github.com/openedx/frontend-app-authn/assets/19806032/551a16cd-ed94-4e38-ae2d-fc320e177759
> fix: Enabling the ability to log in with a username consisting of 2 characters

- src/base-container/components/default-layout/MediumLayout.jsx
- src/base-container/components/default-layout/SmallLayout.jsx
Fixed spacing in authn title in tablet version
> fix: Fixed spacing in tablet version (quince.master)

- public/index.html
The favicon is not currently displaying in Safari. After our investigation, we have found a way to fix it. We used the same approach as what was done in the account mfe. We added the favicon inclusion to the index.html file, and now the favicon is being displayed in Safari.
> fix: Missed favicon in Safari (backport from master)

- src/progressive-profiling/tests/ProgressiveProfiling.test.jsx
- src/recommendations/RecommendationsPageLayouts/SmallLayout.test.jsx
- src/recommendations/tests/RecommendationsList.test.jsx
- src/recommendations/tests/RecommendationsPage.test.jsx
This task involves migrating our existing tests for the 'Welcome Page' and 'Recommendations' functionalities from Enzyme to React Testing Library (RTL).
[VAN-1772](https://2u-internal.atlassian.net/browse/VAN-1772)
> fix: Migrate welcome page and recommendations tests to RTL

- src/register/RegistrationFields/CountryField/CountryField.test.jsx
- src/register/RegistrationFields/EmailField/EmailField.test.jsx
- src/register/RegistrationFields/HonorCodeField/HonorCode.test.jsx
- src/register/RegistrationFields/NameField/NameField.test.jsx
- src/register/RegistrationFields/TermsOfServiceField/TermsOfService.test.jsx
- src/register/RegistrationFields/UsernameField/UsernameField.test.jsx
- src/register/RegistrationPage.test.jsx
- src/register/components/ConfigurableRegistrationForm.test.jsx
- src/register/components/RegistrationFailure.test.jsx
- src/register/components/ThirdPartyAuth.test.jsx
Migrate existing tests for the 'Registration' functionality from Enzyme to React Testing Library (RTL).
[VAN-1769](https://2u-internal.atlassian.net/browse/VAN-1769)
Locally
> fix: Migrate Registration tests to RTL

- Makefile
- package-lock.json
- package.json
Similar to https://github.com/openedx/frontend-app-communications/pull/187.
- install atlas
- remove `--filter` to pull all languages by default
- use ATLAS_OPTIONS to allow custom `--filter`
- include frontend-platform in `atlas pull`
This pull request is part of the [FC-0012 project](https://openedx.atlassian.net/l/cp/XGS0iCcQ) which implements the [Translation Infrastructure update OEP-58](https://docs.openedx.org/en/latest/developers/concepts/oep58.html).
> feat: tutor-mfe compatiblilty for atlas pull | FC-0012 

- .env.development
- src/register/data/utils.js
At present, Authn MFE doesn't work out of the box with devstack settings. These changes allow authn to work with default devstack settings.
Also fixed a bug to validate country field even outside of SHOW_CONFIGURABLE_EDX_FIELDS check. 
Locally
> feat: update default authn settings

- package-lock.json
- package.json
Upgraded Paragon version to v22.1.1
**Reason:** v22.0.0 had an issue of unrecognized prop being passed to DOM which was causing multiple API calls in the MFE. For more details please look at: https://github.com/openedx/paragon/pull/3003
No Jira issue
Locally
> chore: upgrade paragon to v22.1.1

- src/register/RegistrationPage.jsx
- src/register/data/optimizelyExperiment/helper.js
- src/register/data/optimizelyExperiment/useSimplifyRegistrationExperimentVariation.jsx
This PR fixes the following simplify registration experiment bugs
- frontend validations running for password field only on submit
- Step 1 viewed the event being fired twice.
[VAN-1827](https://2u-internal.atlassian.net/browse/VAN-1827)
Locally
|Before|After|
> fix: fix simplify registration experiment bugs

- public/index.html
When accessing Authn MFE for the first time it shows “Auth | null” in the browser header. In this PR we fix If process.env.SITE_NAME is not available it will show  “Authn” Otherwise show “Authn | <site name>”
[VAN-1839](https://2u-internal.atlassian.net/browse/VAN-1839)
|Before|After|
|<img width="265" alt="Screenshot 2024-02-26 at 3 53 42 PM" src="https://github.com/openedx/frontend-app-authn/assets/7627421/7adf84eb-e7b8-49d4-ac33-032e7171b44e">|<img width="235" alt="Screenshot 2024-02-26 at 4 02 39 PM" src="https://github.com/openedx/frontend-app-authn/assets/7627421/1a416522-5c3c-4dd2-a74b-48369ca4c933">|
> fix: browser header showing null

- src/register/RegistrationPage.jsx
- src/register/data/optimizelyExperiment/track.js
To compare the control and variation group for the A/B test where we are measuring the impact of removing username from registration form, added event to default "Register for free" button clicks.
https://2u-internal.atlassian.net/browse/VAN-1827
Locally
> feat: add submit btn click event for default register page

- src/register/data/optimizelyExperiment/helper.js
- src/register/messages.jsx
Changed the CTA text for simplified registration experiment
Locally
|Before|After|
| <img width="1438" alt="Screenshot 2024-02-29 at 11 10 31 AM" src="https://github.com/openedx/frontend-app-authn/assets/52817156/128e2e3d-8033-4694-80a2-b7bb373b04d8"> | <img width="1440" alt="Screenshot 2024-02-29 at 11 07 39 AM" src="https://github.com/openedx/frontend-app-authn/assets/52817156/53c8b7b8-faca-4de2-bded-a101b86aa205"> |
| <img width="1440" alt="Screenshot 2024-02-29 at 11 11 07 AM" src="https://github.com/openedx/frontend-app-authn/assets/52817156/30c4f8dd-dc21-4dfe-bb1e-335e5da83802"> | <img width="1440" alt="Screenshot 2024-02-29 at 11 07 30 AM" src="https://github.com/openedx/frontend-app-authn/assets/52817156/7cf8dfe4-d828-4d37-97b6-d8cf00f9c898"> |
|Before|After| …
> fix: change submit cta text for experiment

- src/register/RegistrationPage.jsx
Removing error alert banner on clicking submit button with valid data.
Locally
> fix: fix error banner alert

- public/index.html
When accessing Authn MFE for the first time it shows "Auth | null" in the browser header. This PR will fix If process.env.SITE_NAME is not available it will show “Authentication” otherwise show “Authentication | {site_name}”. This bug  (#1158) has been fixed in #1168 but still not resolve. As `process.env.SITE_NAME` is `null` but in `index.html`, it assumes `null` as a string value and passed the condition which is expected to be failed. As a result, still showing `Authn | null`. Moreover, in this PR, I have replaced `Authn` with the `Authentication` as suggested [here](https://github.com/openedx/frontend-app-authn/issues/1158#issuecomment-1965850295). 
|Before|After|
|  <img width="482" alt="auth2" …
> fix: browser header showing null and replace authn with Authentication

- src/register/RegistrationPage.jsx
- src/register/data/optimizelyExperiment/helper.js
- src/register/data/reducers.js
- src/register/data/utils.js
- src/register/messages.jsx
Moving the country field to the second step of simplify registration experiment SIMPLIFIED variation.
Locally
> fix: move country field to simplify registration second step

- src/common-components/ThirdPartyAuth.jsx
- src/logistration/Logistration.jsx
- src/logistration/Logistration.test.jsx
There are two changes in this PR
- 1st is done to update the top margin for first appearance of skeleton loader. 
- 2nd is cherry picked from this OSPR: https://github.com/openedx/frontend-app-authn/pull/1086 
[VAN-1837](https://2u-internal.atlassian.net/browse/VAN-1837)
Locally
|Before|After|
|<img width="281" alt="Screenshot 2024-03-05 at 10 25 35 AM" src="https://github.com/openedx/frontend-app-authn/assets/40633976/aa704ed5-ffed-4767-b00a-b30e732c3c55"> |<img width="281" alt="Screenshot 2024-03-05 at 10 25 14 AM" src="https://github.com/openedx/frontend-app-authn/assets/40633976/6ce1e154-c318-4fc9-a8b6-5039cad31269">|
> Fix TPA skeleton loader

- src/register/RegistrationFields/EmailField/EmailField.jsx
- src/register/RegistrationFields/EmailField/EmailField.test.jsx
- src/register/RegistrationFields/EmailField/validator.js
- src/register/RegistrationFields/NameField/validator.js
- src/register/RegistrationPage.jsx
- src/register/RegistrationPage.test.jsx
- src/register/components/ConfigurableRegistrationForm.test.jsx
- src/register/data/actions.js
- src/register/data/reducers.js
- src/register/data/tests/reducers.test.js
- src/register/data/utils.js
The behavior of the registration form is very different from the behavior of this form for the Palm release.
Even with incorrectly filled fields, the form can still be submitted. In certain instances, registration may succeed, such as when the password consists of merely two characters.
There’s an issue where the error message doesn’t disappear even after the error is corrected and the focus is shifted to another field. Here’s how to reproduce it:
1. Fill in all fields correctly.
2. Enter a username or email with a space.
3. Submit a request to create an account.
4. An error will appear in the field where there is a space.
5. The cursor should already be in the field with the error (so there’s no need to click on this field again). Remove the space.
6. Move the cursor to another field.
7. …
> fix: Registration occurs with a password that does not meet the requirements to Quince

- src/sass/_style.scss
This pull request is a backport from the master branch https://github.com/openedx/frontend-app-authn/pull/1165.
The main goal is to make the buttons reflected to the primary paragon color by using the variable provided by the Paragon library.
|Before|After|
| <img width="527" alt="Screenshot at Mar 27 14-03-45" src="https://github.com/openedx/frontend-app-authn/assets/17108583/7448c521-6e77-4186-bcef-d6e13267c489">   | <img width="542" alt="Screenshot at Mar 27 14-01-11" src="https://github.com/openedx/frontend-app-authn/assets/17108583/4262a218-bb4b-4695-a871-d6dbcaca19aa"> |
> [Backport] fix: Update custom SSO buttons to use brand colors

- .github/workflows/ci.yml
We noticed that codecov has stopped running on PRs after updating it to v4. https://github.com/codecov/codecov-action?tab=readme-ov-file#breaking-changes
This happened because tokenless uploading is unsupported in v4. 
Details: https://github.com/openedx/wg-frontend/issues/177
This will be tested on PRs.
> fix: codecov not running on PRs

- src/common-components/SocialAuthProviders.jsx
- src/common-components/ThirdPartyAuth.jsx
- src/register/RegistrationPage.jsx
- src/register/RegistrationPage.test.jsx
- src/register/data/optimizelyExperiment/track.js
- src/register/data/optimizelyExperiment/useMultiStepRegistrationExperimentVariation.jsx
This PR implements multi step registration experiment eventing
[VAN-1907](https://2u-internal.atlassian.net/browse/VAN-1907)
Locally 
|Event|Props|Use|
|:----|:----:|:------:|
| `edx.bi.user.multistepregistration.step1.viewed` | variation | is fired when user falls in a variation and lands on first step of registration |
| `edx.bi.user.multistepregistration.step2.viewed` | variation | is fired when user lands on second step of registration |
| `edx.bi.user.multistepregistration.step3.viewed` | none | is fired when user lands on second step of registration |
| `edx.bi.user.registration.step1.submit.click` | variation | is fired when user clicks CTA on first step of registration page |
| `edx.bi.user.registration.step2.submit.click` | variation | is fired when user clicks CTA on second step …
> feat: add multi step registration eventing

- src/common-components/SocialAuthProviders.jsx
- src/common-components/ThirdPartyAuth.jsx
- src/common-components/messages.jsx
- src/config/index.js
- src/logistration/Logistration.jsx
- src/logistration/Logistration.test.jsx
- src/register/RegistrationPage.jsx
- src/register/RegistrationPage.test.jsx
- src/register/components/ConfigurableRegistrationForm.jsx
- src/register/components/RegistrationFailure.jsx
- src/register/components/tests/ConfigurableRegistrationForm.test.jsx
- src/register/components/tests/RegistrationFailure.test.jsx
- src/register/components/tests/ThirdPartyAuth.test.jsx
- src/register/data/actions.js
- src/register/data/optimizelyExperiment/helper.js
- src/register/data/optimizelyExperiment/track.js
- src/register/data/optimizelyExperiment/useMultiStepRegistrationExperimentVariation.jsx
- src/register/data/reducers.js
- src/register/data/sagas.js
- src/register/data/tests/reducers.test.js
- src/register/data/utils.js
- src/register/messages.jsx
- src/sass/_registration.scss
This PR implements a Multi Step Registration A/B experiment
**Control Variant:** Registration form with 2 steps. (Name, email and password on first step. Username and country of second step).
**Multi-step registration variant:** Registration form with 3 steps. (Email field on first page. Name and password on second page. Username and country on 3rd and last page).
[VAN-1902](https://2u-internal.atlassian.net/browse/VAN-1902)
Locally
**Variation:**
https://github.com/openedx/frontend-app-authn/assets/52817156/f4957f64-450d-4033-a511-dd562f4708f5
**Control:** 
https://github.com/openedx/frontend-app-authn/assets/52817156/7d2c083e-5086-4e18-86d0-f9b781caa889
> feat: implement multi step registration experiment

- src/login/LoginPage.jsx
- src/register/components/ThirdPartyAuth.jsx
This is backport from master - https://github.com/openedx/frontend-app-authn/pull/767
Cosmetic improvements for the login/registration page. Changes in React are related to the situation when third-party login providers is disabled, but when switching between Login and Registration tabs, we still see a preloader that is not necessary in this situation.
https://user-images.githubusercontent.com/19806032/222164313-f1e985d9-47e1-4b18-8b27-8280f5c6a7fd.mov
After making our changes, we no longer see preloaders in cases where third-party login providers are turned off.
https://user-images.githubusercontent.com/19806032/222174870-e76fe894-1a63-448b-bc08-ffd9df8dca0b.mov
> feat: Hide preloaders for third party auth providers if they are disabled

- src/register/RegistrationPage.jsx
- src/register/data/optimizelyExperiment/track.js
Capture the info if the user is a marketing lead (provide email with marketing opt in true) in multi step registration experiment
Locally
> feat: capture marketing lead in experiment events

- src/register/RegistrationFields/CountryField/CountryField.jsx
- src/register/components/ConfigurableRegistrationForm.jsx
Description: 
Add new entry for for another US label which is United States 
[VAN-1900](https://2u-internal.atlassian.net/browse/VAN-1900)
|After|
|-----|
|![image](https://github.com/openedx/frontend-app-authn/assets/12580995/5e95a428-4f99-4652-9ff2-c1d5917aadf1) |
> fix: add new entry for another US label

- src/register/RegistrationPage.test.jsx
- src/register/components/tests/ConfigurableRegistrationForm.test.jsx
- src/register/data/utils.js
- Convert totalRegistrationTime to snake case
[VAN-1816](https://2u-internal.atlassian.net/browse/VAN-1816)
- Tested locally
Here is the backend PR https://github.com/openedx/edx-platform/pull/35333
> fix: change the totalRegisterationTime to snake case

- src/register/components/ConfigurableRegistrationForm.jsx
[INF-1564](https://2u-internal.atlassian.net/browse/INF-1564)
-  To ensure compliance, the country list has been updated to exclude the Russian Federation, preventing new users from registering from the Russian Federation.
- It's a temporary fix. A complete and long-term solution will be implemented in phase 2.
> feat: removed Russian Federation from country list

- .github/workflows/autoupdate-pull-request.yml
- .github/workflows/ci.yml
This code does not have any dependencies that are specific to any specific
version of ubuntu.  So instead of testing on a specific version and then needing
to do work to keep the versions up-to-date, we switch to the ubuntu-latest
target which should be sufficient for testing purposes.
This work is being done as a part of https://github.com/openedx/platform-roadmap/issues/377
closes https://github.com/openedx/frontend-app-authn/issues/1299
> build: Switch to ubuntu-latest for builds

- .eslintignore
- public/index.html
- src/MainApp.jsx
- src/cohesion/index.js
- src/common-components/RedirectLogistration.jsx
- src/common-components/SocialAuthProviders.jsx
- src/index.jsx
[INF-1661](https://2u-internal.atlassian.net/browse/INF-1661)
- Load cohesion script on app load.
- Resolve userId issue on script load.
- SSO provider issue while sending cohesion event
> fix: cohesion script and SSO issue

- src/cohesion/index.js
[INF-1676](https://2u-internal.atlassian.net/browse/INF-1676)
**Description**
In the Authn MFE, we need to send a Segment Identify call that includes the Cohesion anonymous_id as a trait so that Segment is able to map Cohesion’s server-side events with Segment’s client-side events on the same page. 
In [the integration doc](https://docs.google.com/document/d/1HQtyQVrJWFgxH-4-PI5t4SMIH9thPTzc7pP3mNvkNR4/edit?tab=t.0#heading=h.d78647gr4ev3), there is a snippet of code that needs to be added to the already-existing code in Authn MFE to send Identify calls to Cohesion.
> perf: updated cohesion id stitching script

- src/login/LoginPage.jsx
- src/register/RegistrationPage.jsx
[INF-1721](https://2u-internal.atlassian.net/browse/INF-1721)
**Description**
fix cohesion duplicate events post SSO login/registration
> fix: fixed duplicate event firing on post SSO login registration

- src/logistration/Logistration.jsx
This is backport form master - https://github.com/openedx/frontend-app-authn/pull/1086
We found that after clicking twice on the same tab - skeleton appeared and not disappeared till switching other tab or page refresh. We think that it is not logical and our proposal - this minor fix
Before fix:
https://github.com/openedx/frontend-app-authn/assets/19806032/16f7cde0-38a5-4cf9-944c-bac8879f03b6
After fix:
https://github.com/openedx/frontend-app-authn/assets/19806032/2f26ee3a-f1c7-4b24-abc1-f7ed822a9878
> fix: Prevent wrong appearance of skeleton after second tab click

- public/index.html
Description
[INF-1798](https://2u-internal.atlassian.net/jira/software/c/projects/INF/boards/1994?selectedIssue=INF-1798)
We're encountering an issue where the `core.Identify.v1 `call with traits isn't firing reliably. Adding the `defer` attribute to the updated Cohesion snippet might help, as it will ensure the script loads after the DOM is ready.
> fix: adding defer to cohesion script

- src/common-components/data/actions.js
- src/common-components/data/constants.js
- src/common-components/data/reducers.js
- src/common-components/data/sagas.js
- src/common-components/data/service.js
- src/common-components/data/tests/sagas.test.js
- src/register/RegistrationPage.jsx
- src/register/components/ConfigurableRegistrationForm.jsx
- src/register/components/tests/ConfigurableRegistrationForm.test.jsx
We are introducing a feature that allows platform administrators to restrict users from selecting one or more countries in Authn MFE.
We retrieved the list of restricted countries by calling the following API:
👉 https://courses.edx.org/user_api/v1/account/registration/
At the same time, we obtained the translated country names using the i18n-iso-countries package.
Once both datasets were available, we filtered out the restricted countries from the translated list and displayed the updated country list in the UI.
> feat: implemented restricted country implementation

- package-lock.json
- package.json
- src/index.jsx
- src/recommendations/data/tests/hooks.test.jsx
Part 2 of https://github.com/openedx/frontend-app-authn/issues/1422
> feat: upgrade to react 18

- src/logistration/Logistration.jsx
[INF-1858](https://2u-internal.atlassian.net/browse/INF-1858)
A solution for the Cohesion tracking issue on the login/register page.
The problem occurs because Cohesion's pageUrl is set only on the initial page load (/login or /register) and does not automatically update when users switch tabs due to client-side routing (no browser pageView event).
To fix this, a manual pageView event needs to be triggered on the click handler for the 'Register' and 'Sign In' tabs. This forces Cohesion to update its context.
> fix: fixed cohesion pageview

- src/MainApp.jsx
- src/common-components/RouteTracker.jsx
- src/common-components/index.jsx
- src/logistration/Logistration.jsx
[INF-1858](https://2u-internal.atlassian.net/browse/INF-1858)
Description
A solution for the Cohesion tracking issue on the login/register page.
The problem occurs because Cohesion's pageUrl is set only on the initial page load (/login or /register) and does not automatically update when users switch tabs due to client-side routing (no browser pageView event).
To fix this, a manual pageView event needs to be triggered on the click handler for the 'Register' and 'Sign In' tabs. This forces Cohesion to update its context.
> fix: fixed cohesion page url setup

- src/register/RegistrationFields/UsernameField/UsernameField.jsx
- src/register/data/sagas.js
- src/sass/_registration.scss
Username suggestions functionality has been corrected to ensure proper behaviour.
- fixed issue with suggestions being displayed in the wrong place;
- added the ability to navigate through suggestions using the keyboard.
**Related Pull Requests**
PR to the open-release/quince.master branch: https://github.com/openedx/frontend-app-authn/pull/1278
PR to the master branch: https://github.com/openedx/frontend-app-authn/pull/1270
**1. suggestions being displayed in the wrong place**
Open register page -> Enter some string into field "Full name" (e.g. Jack Smith) -> Click on field "Public username"
https://github.com/openedx/frontend-app-authn/assets/40792129/40d292b5-3187-43bc-8325-cadce65b10ce
**2. impossible to enter suggestions field using the keyboard**
Open register page -> Enter some …
> fix: the display of username suggestions

- src/common-components/tests/FormField.test.jsx
- src/forgot-password/tests/ForgotPasswordPage.test.jsx
- src/login/LoginPage.jsx
- src/login/tests/AccountActivationMessage.test.jsx
- src/login/tests/LoginPage.test.jsx
As part of the project for improvements as follow up of react-unit-test-utils, we are going to replace all usages of the deprecated `injectIntl` HOC with the `useIntl()` hook from @edx/frontend-platform/i18n. It is a very straight-forward change, in order to accomplish this we did the following changes:
- In components we have to remove the old `injectIntl`, remove intl as a prop and use the hook instead.
- In tests we need to stop using `injectIntl` and just use the desired component wrapped in a `IntlProvider` (from @edx/frontend-platform/i18n).
Files to refactor:
- src/common-components/tests/FormField.test.jsx
- src/forgot-password/tests/ForgotPasswordPage.test.jsx
- src/login/LoginPage.jsx
- src/login/tests/LoginPage.test.jsx
- src/login/tests/AccountActivationMessage.test.jsx
Closes …
> Replace of injectIntl with useIntl() 1/4

- src/login/tests/ChangePasswordPrompt.test.jsx
- src/login/tests/LoginFailure.test.jsx
- src/logistration/Logistration.test.jsx
- src/progressive-profiling/tests/ProgressiveProfiling.test.jsx
- src/recommendations/RecommendationsPageLayouts/SmallLayout.test.jsx
- src/reset-password/tests/ResetPasswordPage.test.jsx
As part of the project for improvements as follow up of react-unit-test-utils, we are going to replace all usages of the deprecated `injectIntl` HOC with the `useIntl()` hook from @edx/frontend-platform/i18n. It is a very straight-forward change, in order to accomplish this we did the following changes:
- In components we have to remove the old `injectIntl`, remove intl as a prop and use the hook instead.
- In tests we need to stop using `injectIntl` and just use the desired component wrapped in a `IntlProvider` (from @edx/frontend-platform/i18n).
Files to refactor:
- src/login/tests/ChangePasswordPrompt.test.jsx
- src/login/tests/LoginFailure.test.jsx
- src/logistration/Logistration.test.jsx
- src/progressive-profiling/tests/ProgressiveProfiling.test.jsx
- …
> Replace of injectIntl with useIntl() 2/4

- src/register/components/RegistrationFailure.jsx
- src/register/data/constants.js
- src/register/messages.jsx
This PR adds an exception case to handle prevent user registrations with usernames containing forbidden terms.
JIRA
https://2u-internal.atlassian.net/browse/INF-2109
|Before|After|
> chore: Handle forbidden username exceptions on registration
